### ISSUE TITLE
Node stuck at block with synced status.

### ISSUE THREAD

**Issue by EmrePiconbello** [MinaProtocol/mina#7659] opened 2021-01-24 11:49 UTC
The latest release was very stable till got stuck at block 3183 around hours ago. I hope log export catch it. With recent releases when I look at the logs. They don't look chronicle. Finally had a time and looks like that's the case and it makes much confusing from my point.
https://drive.google.com/file/d/1nGPqUwDpeWkXqPnyG8-867n6WS3urmy3/view?usp=sharing

**Comment by Kakashi010** [comment] 2021-01-24 12:06
I also had the same issue with one of my nodes on G cloud (8vCPU, 32GB). After 14 hours in sync node was stuck for at least 4 hours with 'Synced' status. I did exported the logs but unfortunately didn't save it locally before reinstalling mina :( FYI, my bare matal (12 cpu, 16gb) is going good with 1d 3h+ uptime. Running only BP on both.

**Comment by Y0Y0jojo** [comment] 2021-01-24 23:15
[mina-log.txt](https://github.com/MinaProtocol/mina/files/5863408/mina-log.txt)
Im having a similar issue. the current block is 3482 but my synced node thinks its 3296. i lost 2 block producer slots in 2 days with this newest version FYI. Im also noticing my fan is running all the time now at full speed. before this version it would only go full blast during block production.

**Comment by Kakashi010** [comment] 2021-02-01 09:03
Current **block height 4799**. Node **stuck at 4721**. Uptime: **1d17h**. Platform: **Gcloud 8v32G**.

![image](https://user-images.githubusercontent.com/38396843/106435975-bdaff300-649d-11eb-98f4-8d33ac0c3ebc.png)

**Comment by podlodkin** [comment] 2021-02-03 19:04
The same situation for 0.2.12 release.

My node uptime is 1d14h. Peers count us 73. Synced status (see screenshot). 
But block height is only 4993 (actual is 5193!).
I just now produced a new red 4993 block: https://minaexplorer.com/block/3NK3b8CCHsoVGj82yEPsNp4zCRbnSLwCZs35a86A8ccYnqeM6kTh
My node was synced and outtdated in the same time.
It's seems a bug.
P.s. There are some others outdated blocks in explorer in last 24 hours (!!!).

![image](https://user-images.githubusercontent.com/23024800/106795902-58a5fa00-6663-11eb-8fd4-5efa7337f750.png)

**Comment by mrmr1993** [comment] 2021-03-22 02:26
Closing this as a duplicate of #7555.

The underlying issue is that the verifier process sometimes isn't restarted if it exits or crashes, which prevents us from verifying any new blocks after that point. There's a fix in #8196, which we're currently testing and hope to release soon.

**Closed by mrmr1993** 2021-03-22 02:26 UTC
