### ISSUE TITLE
Testnet 4.1: Can't sync, cyclic reboots

### ISSUE THREAD

**Issue by c29r3** [MinaProtocol/mina#6768] opened 2020-11-19 17:46 UTC
## Description  
Node can't sync. The status displays 1 block and after about 30 minutes the docker container restarts

<details>
  <summary>Coda client status </summary>

```
Coda daemon status
-----------------------------------

Global number of accounts:       1026
Block height:                    1
Max observed block length:       218
Local uptime:                    13m19s
Ledger Merkle root:              jxqupp5oGcqRuEFGaq9oTtJYBdMdtgHodLoxuMk7xt4m8gBUnNx
Protocol state hash:             3NLVs8hfDhTvzEcjXurQdGKS1ykj6GcYKS1gXdHcNM1MorkbBEBX
Chain id:                        ef95774fb2ed657da61bfc40a8a148a9c9a202476b539aaf915e6cd81d1ef268
Git SHA-1:                       [DIRTY]757342b6cef510f13cb5ad2fbad97518d6df45df
Configuration directory:         /root/.coda-config
Peers:                           55 (35.197.55.249:8302 161.97.84.68:8302 44.234.67.117:8302 111.132.5.7:50054 34.75.61.180:10505 167.86.104.204:8302 35.231.227.169:10504 34.74.216.121:10509 34.74.107.15:10511 95.216.37.122:8302 35.233.205.29:8302 198.84.232.42:59942 134.249.187.129:8302 195.2.70.184:8302 35.225.94.177:8302 35.243.252.28:8302 35.185.55.185:10513 149.74.248.92:8302 167.86.111.224:8302 95.216.223.106:8302 51.143.39.184:8302 168.119.64.26:8302 135.181.77.184:8302 167.86.109.191:8302 34.73.206.59:10503 35.223.11.237:8302 34.75.103.6:10401 35.229.97.85:10501 35.227.120.14:10512 35.237.137.82:10515 139.162.136.96:8302 35.227.13.96:10001 194.19.235.76:8302 49.50.163.24:8302 5.189.140.233:8302 78.47.65.132:8302 34.75.48.118:10514 69.164.197.183:48956 34.73.254.106:10506 5.189.177.252:8302 34.74.76.116:10502 116.203.197.191:8302 34.89.255.165:60254 173.249.2.99:8302 34.75.30.199:10516 35.237.228.219:10508 5.188.159.227:8302 78.47.27.79:8302 34.66.142.59:8302 34.222.195.254:59064 35.237.148.187:10507 35.243.211.158:10001 168.119.111.123:8302 14.52.147.51:56702 35.231.245.46:10510)
User_commands sent:              0
SNARK worker:                    None
SNARK work fee:                  25000000
Sync status:                     Catchup
Block producers running:         1 (B62qp6PvbR69ip9a1ZRy47ryGqVSWVrWJ19fhPVDJBZ6x2S8AKyL5Lc)
Best tip consensus time:         epoch=0, slot=0
Next block will be produced in:  in 3.037h
Consensus time now:              epoch=0, slot=690
Consensus mechanism:             proof_of_stake
Consensus configuration:         
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Genesis state timestamp:   2020-11-18 07:11:20.000000Z
        Acceptable network delay:  3m

Addresses and ports:             
        External IP:    95.165.167.193
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWNnFoeFFRRD7cTC5iegyeM3AobSPK3RUtob1WoA7pBZwn
        Libp2p port:    8302
        Client port:    8301

```

</details>  

## Environment  
```
Git SHA-1: [DIRTY]757342b6cef510f13cb5ad2fbad97518d6df45df
Host OS: Ubuntu 20.04  
Using containerization: docker  
CPU: i7 9500  
RAM: 16 GB  
```

## Steps to reproduce  
1. Forwarded ports on my router: 8302, 8303\TCP  
2. Run docker container
```
cd; docker run --name mina -d \
--restart always \
-p 8301-8305:8301-8305 \
-p 127.0.0.1:3085:3085 \
-v $(pwd)/keys:/root/keys:ro \
-v $(pwd)/coda-config:/root/.coda-config \
-v $(pwd)/peers.txt:/root/peers.txt \
--env CODA_PRIVKEY_PASS='12345' \
minaprotocol/mina-daemon-baked:4.1-turbo-pickles-mina757342b-auto811bf26 daemon \
-block-producer-key /root/keys/my-wallet \
-peer-list-file /root/peers.txt \
-insecure-rest-server \
-log-level Info
```  

## LOGS  
https://drive.google.com/drive/folders/1A-lSR-FVeG2mNwfZH61wl0JfIBXTLtoj?usp=sharing

**Comment by EmrePiconbello** [comment] 2020-11-19 20:14
Same issue without docker 

LOGS 

https://drive.google.com/file/d/1LD-k3u4MBYmW96UMXggUX9KNTL6bgn_7/view?usp=sharing
https://drive.google.com/file/d/1u1b4ehC06UAaHs1nHTgz87KMpUvlaUAp/view?usp=sharing

**Comment by bkase** [comment] 2020-11-19 20:58
> Also seeing a lot of RPC call error for "get_transition_chain" so it seemingly can't get what it needs

If this is helpful ^^

**Comment by garethtdavies** [comment] 2020-11-19 21:02
Likely not the cause but seeing a large amount of gossiped snark work, which is rejected. Not sure if this is detrimental to the performance of the node during catchup?

```
Rejecting gossiped snark work $stmt, statement not referenced
```

**Comment by aneesharaines** [comment] 2020-12-01 21:32
Suspect this was already fixed in the new version

**Comment by aneesharaines** [comment] 2020-12-03 00:31
Thanks @c29r3 for reporting this!  This should be fixed in the latest version.  If you see this again on the latest please reopen the issue so investigate.  Much appreciated!

**Closed by aneesharaines** 2020-12-03 00:31 UTC
Labels: bug
