### ISSUE TITLE
Daemon stop about 1h30 after launch

### ISSUE THREAD

**Issue by bidulemachin** [MinaProtocol/mina#6480] opened 2020-10-22 20:43 UTC
I updated my node at about 5:30PM (Paris Time): 

Coda daemon status at this time :
-----------------------------------

Max observed block length:  1
Local uptime:               7m46s
Chain id:                   b07ab5f2faf92513f9406718b35b897cbfa3bf5dcaff6ea4d7e02d9a3ae4cbaa
Git SHA-1:                  [DIRTY]2847b2c35bbdfc0f38674ab1922dabd5ec84ae0e
Configuration directory:    /home/machin/.coda-config
Peers:                      21 (34.75.115.51:10001 195.201.82.50:8302 35.196.217.130:10506 35.227.103.155:10501 34.72.109.165:8302 35.231.91.32:10509 35.243.238.16:10001 34.75.43.44:10001 34.75.58.206:10505 34.74.57.210:10503 35.235.118.191:8302 78.193.188.67:41055 34.75.81.35:10401 35.196.217.130:10504 144.91.80.137:8302 167.86.104.204:8302 138.68.24.82:8302 35.231.109.60:10508 35.231.48.182:10510 35.231.91.32:10502 35.231.48.182:10507)
User_commands sent:         0
SNARK worker:               None
SNARK work fee:             25000000
Sync status:                Bootstrap
Block producers running:    1 (B62qpLzFKS3PQc42uKYv3JHQj6FaZSChw2dT9BpLni25QRyL6EzCL33)
Consensus time now:         epoch=0, slot=230
Consensus mechanism:        proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         20
        c:                         8
        c * k:                     160
        Slots per epoch:           480
        Slot duration:             3m
        Epoch duration:            1d
        Genesis state timestamp:   2020-10-22 04:08:56.000000Z
        Acceptable network delay:  3m

Addresses and ports:
        External IP:    5.189.140.233
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWG5SNC33nrsz2TQQqANf2VBULVVo4xvALtSMkvErEXdvc
        Libp2p port:    8302
        Client port:    8301

--------------------------------------------

But about 1 hour later, the process stopped (time of last update in log file)

[coda-log.zip](https://github.com/MinaProtocol/mina/files/5425633/coda-log.zip)

**Comment by nholland94** [comment] 2020-11-11 20:23
The output of your log does not indicate any error, and it does not appear that the daemon received any exit signals that it tried to handle. It's possible that your daemon ran out of memory or got sent a SIGKILL signal by your OS. If there is a core dump or crash log, please attach that instead.

If your daemon was stuck in bootstrap for > 1 hour with a max observed block height == 1, this indicates that your node likely was not able to communicate with the network. This most frequently happens if your ports are not correctly forwarded. This wouldn't be the reason why your node crashed, but it is likely the reason your node never synced.

FYI, the archive you uploaded is titled *.zip, but it's actually a gzip'd tar archive, which should be *.tar.gz. Took me a little bit to figure out how to actually extract it because of this, since unziping this results in an error. This log is also from direct output captured via the daemon stdout, but for debugging purposes, it is more useful if you can provide us the json log in the future, which can be found at `~/.coda-config/coda.log`. This log format has more verbose information which is necessary to debug many issues.

I'm going to close this issue for now, but if you are able to reproduce this with a crash in the log, please go ahead and make a new issue so that we can take a look at that and investigate what is happening.

**Closed by nholland94** 2020-11-11 20:23 UTC
Labels: bug
