### ISSUE TITLE
☠  Coda Daemon crashed.

### ISSUE THREAD

**Issue by cheoa** [MinaProtocol/mina#6960] opened 2020-12-06 09:59 UTC
[summary.txt](https://github.com/MinaProtocol/mina/files/5648564/summary.txt)

**Comment by garethtdavies** [comment] 2020-12-07 02:15
`Failure","failed to initialize transition frontier: Staged_ledger.of_scan_state_and_ledger : did not connect with snarked ledger hash"`

This is a duplicate of https://github.com/MinaProtocol/mina/issues/6950

**Comment by mrmr1993** [comment] 2021-03-18 03:04
Closing in favour of #6950, which includes more logs.

**Closed by mrmr1993** 2021-03-18 03:04 UTC
