### ISSUE TITLE
Daemon crashing due to libp2p crashes

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#14382] opened 2023-10-18 17:26 UTC
On ITN, we are seeing a decent number of crashes when handling libp2p helper stderr output (213 crashes observed across the network over 24 hours). It appears that we failing to catch a json error in the case where we cannot parse the stderr output as a json log file.

### Originating Backtrace
```
Raised at Yojson.json_error in file "common.ml", line 5, characters 19-39,
Called from Yojson.Safe.read_json in file "lib/read.ml" (inlined), line 1025, characters 3-39,
Called from Yojson.Safe.from_lexbuf in file "lib/read.mll", line 1109, characters 8-26,
Called from Yojson.Safe.from_string in file "lib/read.mll", line 1122, characters 6-26,
Called from Mina_net2__Libp2p_helper.spawn.(fun) in file "src/lib/mina_net2/libp2p_helper.ml", line 265, characters 51-79
```

### Toplevel Exception
```
monitor.ml.Error, Mina_net2__Libp2p_helper.Libp2p_helper_died_unexpectedly,
Raised at Mina_net2__Libp2p_helper.handle_libp2p_helper_termination in file "src/lib/mina_net2/libp2p_helper.ml", line 144, characters 8-45,
Called from Async_kernel__Deferred0.bind.(fun) in file "src/deferred0.ml", line 54, characters 64-69,
Called from Async_kernel__Job_queue.run_job in file "src/job_queue.ml" (inlined), line 128, characters 2-5,
Called from Async_kernel__Job_queue.run_jobs in file "src/job_queue.ml", line 169, characters 6-47,
Caught by monitor at file "src/lib/gossip_net/libp2p.ml", line 236, characters 31-31
```

**Comment by deepthiskumar** [comment] 2023-12-06 20:50
Duplicate of #14383

**Closed** 2023-12-06 20:50 UTC
Labels: itn3, Testworld-2-0-protocol-performance-testing
