### ISSUE TITLE
Testnet 4.1: "writer buffer has data older than",["maximum_age","2m"

### ISSUE THREAD

**Issue by Cris-F** [MinaProtocol/mina#6790] opened 2020-11-20 15:53 UTC
### Logs:  [2020-11-20_14-34-18.zip](https://github.com/MinaProtocol/mina/files/5574602/2020-11-20_14-34-18.zip)
`
CrisF
Host OS: Ubuntu 18.04  
CPU: 8 core  
RAM: 40 GB  
`
### Description

Block Producer crashed after ~2hr10min reaching _catchup_.  Related to #6766 ? Saw mentions of this issue in Discord.
Discord: 
https://discord.com/channels/484437221055922177/754653322845356103/779030599917895740
https://discord.com/channels/484437221055922177/583400552487059546/779242763241390080
https://discord.com/channels/484437221055922177/746316198806814760/779302537253355542
```["2020-11-20","13:38:31.532145630Z"],["2020-11-20","13:38:33.325359084Z"],["2020-11-20","13:38:42.674216732Z"],["2020-11-20","13:38:45.451470258Z"],["2020-11-20","13:38:46.635075937Z"],["2020-11-20","13:38:49.067359301Z"]]],["bytes_seen","20225091"],["too_old",["Full",[]]]]]],["consumer_left","Empty"],["raise_when_consumer_leaves","false"],["open_flags",["Full",["Ok",["rdwr","nonblock"]]]],["line_ending","Unix"]]]],["Caught by monitor (id 87523)"]]]]]],["connection_description",["Client connected via TCP",["localhost","29088"]]],["rpc_tag","rpc_parallel_plain_0"],["rpc_version","0"]]}
[0;31m[2020-11-20 13:39:43.297408]Network_pool__Transaction_pool: Error verifying transaction pool diff from $sender: $error[0m
$sender = {"Remote":{"host":"148.251.236.112","peer_id":"12D3KooWFXcdwiJ5m8VTz7mHV3bmc7n7Jrgrcw8NjFJakrzignpX","libp2p_port":8302}}
$error = {"sexp":[["rpc_error",["Connection_closed",[["exn raised in RPC connection Writer.t",["monitor.ml.Error",["writer buffer has data older than",["maximum_age","2m"],["beginning_of_buffer","\u0001\u0014rpc_parallel_plain_1\u0000\FE\B9\u0017\FEK```
[2020-11-20_14-34-18.zip](https://github.com/MinaProtocol/mina/files/5574603/2020-11-20_14-34-18.zip)
...
```[0;35m[2020-11-20 13:39:43.332401]Dune__exe__Coda: Daemon child process 19890 terminated with exit code 0[0m
[0;31m[2020-11-20 13:39:43.332437]Child_processes__Termination: Child process of kind "Verifier" with pid 19890 has terminated[0m```
### Logs
[2020-11-20_14-34-18.zip](https://github.com/MinaProtocol/mina/files/5574560/2020-11-20_14-34-18.zip)

**Comment by gregbostrom** [comment] 2020-11-20 17:44
I had the same problem.
Debian GNU/Linux 9.13 (stretch)
64MB Ram, 850GB SSD, 8CPU Core

[invLogCall.tar.gz](https://github.com/MinaProtocol/mina/files/5575221/invLogCall.tar.gz)

**Comment by bkase** [comment] 2020-11-20 20:17
Dupe of #6766 but thanks for the logs! Anyone who ends up here, please put info in the comments of that issue

**Closed by bkase** 2020-11-20 20:17 UTC
