### ISSUE TITLE
Add a 'waiting' status for nodes before the network starts

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#14846] opened 2024-01-12 21:24 UTC
This was previously implemented in the now-stale PR https://github.com/MinaProtocol/mina/pull/7240

**Comment by emberian** [comment] 2024-02-02 01:25
closing as a dupe of https://github.com/MinaProtocol/mina/issues/7091

**Closed by emberian** 2024-02-02 01:25 UTC
