### ISSUE TITLE
General crash of sorts

### ISSUE THREAD

**Issue by jflowers1974** [MinaProtocol/mina#6909] opened 2020-12-02 15:50 UTC
Woke up to my node down, and the usual means I've restarted seem to not work.
[coda_crash_report_2020-12-02_15-48-15.646566.tar.gz](https://github.com/MinaProtocol/mina/files/5630429/coda_crash_report_2020-12-02_15-48-15.646566.tar.gz)

**Comment by jflowers1974** [comment] 2020-12-02 16:04
Tried "sudo rm -f ~/.coda-config/.mina-lock" after an uninstall/reinstall/reboot even:

Can't seem to get back up and running.  

[coda_crash_report_2020-12-02_16-02-51.550990.tar.gz](https://github.com/MinaProtocol/mina/files/5630500/coda_crash_report_2020-12-02_16-02-51.550990.tar.gz)

**Comment by garethtdavies** [comment] 2020-12-02 18:05
```
"Exception":{"sexp":["Zexe_backend_common.Curve.Make(BaseField)(ScalarField)(Params)(C).Affine.Stable.V1.Invalid_curve_point(_)"]
```

**Comment by garethtdavies** [comment] 2020-12-02 18:06
Duplicate of https://github.com/MinaProtocol/mina/issues/6901

**Closed** 2020-12-03 19:43 UTC
