### ISSUE TITLE
Rosetta: Re-enable the disabled tests, ensure it's on CI

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9293] opened 2021-07-27 17:08 UTC

**Comment by robinbb** [comment] 2022-10-12 01:57
@lk86 @aneesharaines Is there more to do here? (I'm not sure which the disabled tests were.)

**Comment by kantp** [comment] 2022-10-17 08:47
Duplicate of #9332

**Closed** 2022-10-31 06:31 UTC
Labels: rosetta
