### ISSUE TITLE
Test Plan: Archive Node

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#8935] opened 2021-05-25 17:51 UTC

**Comment by psteckler** [comment] 2021-06-08 17:08
https://www.notion.so/minaprotocol/Archive-Node-e28c4722fba74635bd9f7c18c7e2bfa3

**Comment by robinbb** [comment] 2022-10-13 14:47
@psteckler @deepthiskumar Can the Mina Foundation engineering team take this issue?

**Comment by trevorbernard** [comment] 2023-01-30 16:51
@robinbb May someone give me access to the test plan linked in the notion? I don't have permission.

**Comment by robinbb** [comment] 2023-04-09 01:36
@trevorbernard I do not have access to the Notion page, either.

Probably, this is a case where the Notion page was intended to have the details of the plan.

Also, it is probable that the plan no longer makes sense because of other work that has been done in the last years.

@psteckler @deepthiskumar @nholland94 @aneesharaines If you want the Granola team to execute the test plan, please paste the content of the plan here in a comment or in the description. If it is safe to close this issue because the plan no longer makes sense, please do so.

**Comment by psteckler** [comment] 2023-04-09 02:42
I would say the plan is out-of-date, there are better ways to test the archive db.

**Closed by psteckler** 2023-04-09 02:42 UTC
Labels: archive-node, Proj - test plans
