### ISSUE TITLE
Dumping the next staking ledger returns current ledger

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#7480] opened 2021-01-14 17:35 UTC
On a node that is in epoch 1 and hence, the next epoch ledger should be the snarked ledger of the last block of epoch 0 both staking ledgers are the same. You can reproduce this via:

```
coda advanced dump-staking-ledger next -json > stakingnext.json
coda advanced dump-staking-ledger current -json > staking.json
cmp --silent staking.json stakingnext.json && echo '### Files Are Identical! ###' || echo '### Files Are Different! ###'
```

This will confirm the files are identical. I have reproduced this on several synced nodes.

Running `Commit [DIRTY]16ebdd6597ab050fdaf8a075cc39d9b7be1233cf on branch HEAD`

I also confirmed the raw block data returns correctly. The last block of epoch 0:

```
{ 
    "creator" : "B62qmkfggYyKGwSooz37C9dPoh6Mnxti9AUzXhHiena7p3fisPdsXwQ", 
    "stateHash" : "3NLdAqxtBRYxYbCWMXxGu6j1hGDrpQwGkBDF9QvGxmtpziXQDADu", 
    "stateHashField" : "4997944857633809284172497167423885262957197606388715384450895735278942062289", 
    "protocolState" : {
        "blockchainState" : {
            "date" : "1610639430000", 
            "snarkedLedgerHash" : "jx7XXjRfJj2mGXmiHQmpm6ZgTxz14udpugyFtw4DefJFpie7apN", 
            "stagedLedgerHash" : "jxcb8TqksxvGsiueThMACdAENVei2kW99VvezD3t46gSpFVAGBz", 
            "utcDate" : "1610639430000"
        }, 
        "consensusState" : {
            "blockHeight" : "1768", 
            "blockchainLength" : "1768", 
            "epoch" : "0", 
            "epochCount" : "0", 
            "hasAncestorInSameCheckpointWindow" : true, 
            "lastVrfOutput" : "EiRsT7V8nseQ2esRorw9HR6t2VsQrVaGmNEAPgwq9sThW1YtWE3dT", 
            "minWindowDensity" : "1", 
            "slot" : "7132", 
            "totalCurrency" : "166536600000001000", 
            "stakingEpochData" : {
                "epochLength" : "1", 
                "lockCheckpoint" : "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x", 
                "ledger" : {
                    "hash" : "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R", 
                    "totalCurrency" : "165950000000001000"
                }, 
                "seed" : "2va9BGv9JrLTtrzZttiEMDYw1Zj6a6EHzXjmP9evHDTG3oEquURA", 
                "startCheckpoint" : "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x"
            }, 
            "nextEpochData" : {
                "epochLength" : "1769", 
                "ledger" : {
                    "hash" : "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R", 
                    "totalCurrency" : "165950000000001000"
                }, 
                "lockCheckpoint" : "3NK5G8Xqn1Prh3XoTyZ2tqntJC6X2nVwruv5mEJCL3GaTk7jKUNo", 
                "seed" : "2vb1Mjvydod6sEwn7qpbejKCfRqugMgyG3MHXXRKcAkwQLRs9fj8", 
                "startCheckpoint" : "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x"
            }, 
            "slotSinceGenesis" : "7132"
        }, 
        "previousStateHash" : "3NLsnmrCQo5BqM9iF52B56StmAAHP9G9wzmQdukWimDf3e3kPfxn"
    }, 
```

The first block of epoch 0, which correctly lists the next staking ledger hash:

```
{ 
    "creator" : "B62qkw56qGURA5H9gMuwhtv6CvPmPXqirVrUjNyKHgYEHju1iM2kii3", 
    "stateHash" : "3NLH5xhWgLvBzrNydkvB5e7YgqthGFjLewP7PZfhGHeNUCrWnfnw", 
    "stateHashField" : "24512709561306590767168451881575626440384096996542194081942762377652396420259", 
    "protocolState" : {
        "blockchainState" : {
            "date" : "1610641770000", 
            "snarkedLedgerHash" : "jxTizy6RyyrEz6nBcNsrgFXmfiDnGyoaVinr2aH86hq4mPvAHbS", 
            "stagedLedgerHash" : "jwK23PCqugf8TzoGmxDa2aY2o2DEaHmThKoutg4xd8rjTPPCHb5", 
            "utcDate" : "1610641770000"
        }, 
        "consensusState" : {
            "blockHeight" : "1769", 
            "blockchainLength" : "1769", 
            "epoch" : "1", 
            "epochCount" : "1", 
            "hasAncestorInSameCheckpointWindow" : true, 
            "lastVrfOutput" : "EiRt8xEp2oRxUXK9UbcxuXLhcoG5g2hmrw7eRVmAPx6uJ7rSECxsb", 
            "minWindowDensity" : "1", 
            "slot" : "5", 
            "totalCurrency" : "166537000000001000", 
            "stakingEpochData" : {
                "epochLength" : "1769", 
                "lockCheckpoint" : "3NK5G8Xqn1Prh3XoTyZ2tqntJC6X2nVwruv5mEJCL3GaTk7jKUNo", 
                "ledger" : {
                    "hash" : "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R", 
                    "totalCurrency" : "165950000000001000"
                }, 
                "seed" : "2vb1Mjvydod6sEwn7qpbejKCfRqugMgyG3MHXXRKcAkwQLRs9fj8", 
                "startCheckpoint" : "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x"
            }, 
            "nextEpochData" : {
                "epochLength" : "1", 
                "ledger" : {
                    "hash" : "jx7XXjRfJj2mGXmiHQmpm6ZgTxz14udpugyFtw4DefJFpie7apN", 
                    "totalCurrency" : "166537000000001000"
                }, 
                "lockCheckpoint" : "3NLdAqxtBRYxYbCWMXxGu6j1hGDrpQwGkBDF9QvGxmtpziXQDADu", 
                "seed" : "2vbh885rYdGzo8zvscgKwC9m2pbrdU5hYwx35G9VBRFxpwZuhDEe", 
                "startCheckpoint" : "3NLdAqxtBRYxYbCWMXxGu6j1hGDrpQwGkBDF9QvGxmtpziXQDADu"
            }, 
            "slotSinceGenesis" : "7145"
        }, 
        "previousStateHash" : "3NLdAqxtBRYxYbCWMXxGu6j1hGDrpQwGkBDF9QvGxmtpziXQDADu"
    }, 
```

**Comment by bkase** [comment] 2021-01-14 23:30
I can confirm that `coda advanced dump-staking-ledger next` does correctly pull from `Consensus.Data.Local_state.next_epoch_ledger` via mina_lib.ml . Maybe @deepthiskumar or @nholland94 can comment on why these ledgers are still the same?

**Comment by nholland94** [comment] 2021-01-15 00:04
If this is at epoch 1, these will still be the same unless a scan state has been fully filled (and thus a proof has been emitted from the staged ledger). Even past epoch 1, these can be the same if a scan state has not been filled for at least 2 epochs in a row.

**Comment by garethtdavies** [comment] 2021-01-15 00:18
Maybe I am fundamentally misunderstanding this but as per the output above shouldn't the ledger hash printed here be what should be returned?

```
"nextEpochData" : {
                "ledger" : {
                    "hash" : "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R", 
                    "totalCurrency" : "165950000000001000"
                }
            }
```

**Comment by deepthiskumar** [comment] 2021-01-15 02:31
`jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R` is the genesis ledger hash. You meant this?
```"nextEpochData" : {
                "ledger" : {
                    "hash" : "jx7XXjRfJj2mGXmiHQmpm6ZgTxz14udpugyFtw4DefJFpie7apN", 
                    "totalCurrency" : "166537000000001000"
                }```

The epoch ledgers you are seeing are still from epoch 0. The ledgers get updated (staking <- next and next <- snarked ledger) when the first block in the new epoch is finalized. The cli command could check this condition and return the appropriate ledger at any given point but that could change given the first block in the new epoch is not finalized yet. Alternatively, the command could return nothing until the first block is finalized and then show the final `next` ledger. I like the second solution a bit better because it will not cause any unnecessary confusion about what the `next` ledger is

**Comment by garethtdavies** [comment] 2021-01-15 02:38
> `jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R` is the genesis ledger hash. You meant this?

No, this would be the staking ledger for epoch 2 so not the genesis ledger.  I'm trying to show what the staking ledger will be for the next epoch not this one - which is given by the following which _is_ the genesis ledger as expected.

```
"stakingEpochData" : {
                "ledger" : {
                    "hash" : "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R", 
                    "totalCurrency" : "165950000000001000"
                }
            }, 
```

> The ledgers get updated (staking <- next and next <- snarked ledger) when the first block in the new epoch is finalized

This is the issue. So I need to wait 290 blocks for this to return correctly. Agree either solution you propose is better than this that just returns something that is almost certainly wrong vs nothing or a non-finalized ledger.

**Comment by deepthiskumar** [comment] 2021-01-15 02:50
Yeah, I'll make a PR to change that to return nothing.

Just to clarify: `jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R` is the genesis ledger hash as specified in the protocol state 
From one of the blocks
```
       blockchain_state: {
        genesis_ledger_hash: "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R"         
        snarked_ledger_hash: "jxYSRsBenH9gvMNsjx2GdUpvQdRgLDYJ5ygbMxSrLHqq1zckPEo"         
        snarked_next_available_token: "2"         
        staged_ledger_hash: {…}         
        timestamp: "1610616750000"         
       }
       consensus_state: {
        block_creator: "B62qmBtAho32ZtAfnRp7iHEczHW64VsJRVDGAv3LbAMXUk8yjrAU1Sy"         
        block_stake_winner: "B62qmBtAho32ZtAfnRp7iHEczHW64VsJRVDGAv3LbAMXUk8yjrAU1Sy"         
        blockchain_length: "1705"         
        ```
And so it is the staking ledger for epoch 0 and epoch 1.

Staking ledger hash for epoch 2 will be `jx7XXjRfJj2mGXmiHQmpm6ZgTxz14udpugyFtw4DefJFpie7apN` as shown in the block from epoch 1 you pasted above (if it remains in the best chain, that is)

**Comment by garethtdavies** [comment] 2021-01-15 03:17
@deepthiskumar thanks yes, I copied the wrong hash in my later comment 😖 `jx7XXjRfJj2mGXmiHQmpm6ZgTxz14udpugyFtw4DefJFpie7apN` is the hash I am interested in - the staking ledger of epoch 2 (currently unfinalized).

Thinking about it, I think the better approach is returning the unfinalized ledger rather than empty (knowing that it could change much like anything else). I'm mainly thinking of this from the perspective of say a user knowing their delegation has made it into the staking ledger without a. huge delay - in that sense it is similar to a payment confirmation which also wouldn't be confirmed for `k` blocks.

**Comment by deepthiskumar** [comment] 2021-01-16 01:53
We can make it so that it returns the tentative next-epoch-ledger but it would be expensive to generate that. We currently store only one snarked ledger at the root (finalized block) and generating the next epoch ledger would involve replaying the transactions for each merge proof that was emitted until the last block of the epoch. This would be (k-1)*128 transactions worst case. We could cache the generated next-epoch-ledger but that could be large given the number of transactions that maybe involved. Also, it has to be recomputed whenever if there is a reorg. So issuing this on a block producer node frequently might not be a good idea. Just want to bring this up before I start implementing. Also, will put this behind a flag and by default the command returns nothing or the finalized ledger

**Comment by garethtdavies** [comment] 2021-01-16 15:22
I can confirm this works as expected past 290 blocks 💥 

Regarding the complications with the above. To be clear, this isn't urgent for me (the current staking ledger was) - there is still a large amount of time after k blocks in an epoch for this to be useful. What would be nice is to replicate what exists with the current ledger when you try to get during bootstrap where it emits a warning that it isn't available so maybe as an interim solution it could return the next staking ledger is not available until finalized or somesuch?

**Comment by deepthiskumar** [comment] 2021-01-22 05:57
What would be nice is to replicate what exists with the current ledger when you try to get during bootstrap where it outputs that it isn't available. So maybe it could return the next staking ledger is not available until finalized or somesuch?

Yeah,this is a straightforward change

**Comment by psteckler** [comment] 2021-02-19 19:58
Closing because #7612

**Closed by psteckler** 2021-02-19 19:58 UTC
