### ISSUE TITLE
Unable to connect to Mina daemon

### ISSUE THREAD

**Issue by thecoldblooded** [MinaProtocol/mina#14408] opened 2023-10-22 18:14 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Mina Daemon crashed

### Steps to Reproduce

1.mina client status
2.
3.
...

### Expected Result

Global number of accounts:                     201745
Block height:                                  1644
Max observed block height:                     1644
Max observed unvalidated block height:         1644
Local uptime:                                  4d20h23m12s
Ledger Merkle root:                            jwNVTBGzjwVKor7ZxpK6xNowVPyaGUHBdiBdU3GYRfwAs4atoKP
Protocol state hash:                           3NLCfPFDeqFxa2J312V1jGifoDupaVF2iPztuYFJnSLYY6sEVV1d
Chain id:                                      332c8cc05ba8de9efc23a011f57015d8c9ec96fac81d5d3f7a06969faf4bce92
Git SHA-1:                                     55b78189c46e1811b8bdb78864cfa95409aeb96a
Configuration directory:                       /root/.mina-config/
Peers:                                         155
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Synced
Catchup status:
        Finished:  496

Block producers running:                       1 (B62qnKexFyFub6M6mhT3Va3C5kEEUcajb33rzoNWzQasY81oGTSMV5p)
Coinbase receiver:                             Block producer
Best tip consensus time:                       epoch=0, slot=2325
Best tip global slot (across all hard-forks):  2325
Next block will be produced in:                in 2.105d for slot: 3337 slot-since-genesis: 3337 (Generated from consensus at slot: 2270 slot-since-genesis: 2270)
Consensus time now:                            epoch=0, slot=2326
Consensus mechanism:                           proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2023-10-17 16:01:01.000000Z
        Acceptable network delay:  3m

Addresses and ports:
        External IP:    89.252.188.42
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWDjLZ3MzJNFLGsVSy5XCci2sgHg9mDaay7GmZNp9q3Qrs
        Libp2p port:    8302
        Client port:    8301

Metrics:
        block_production_delay:             7 (5 0 0 0 0 0 0)
        transaction_pool_diff_received:     5
        transaction_pool_diff_broadcasted:  0
        transactions_added_to_pool:         7140
        transaction_pool_size:              1
        snark_pool_diff_received:           48
        snark_pool_diff_broadcasted:        0
        pending_snark_work:                 0
        snark_pool_size:                    2758

### Actual Result

Oct 22 18:03:33 ubuntu mina[721278]: {"timestamp":"2023-10-22 18:03:33.043096Z","level":"Debug","source":{"module":"Init__Mina_run","location":"File \"src/app/cli/src/init/mina_run.ml\", line 99, characters 2-14"},"message":"Successfully wrote the visualization of the registered masks at location: /root/.mina-config/coda_crash_report_2023-10-22_18-03-33.042861/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","host":"5.180.186.25","peer_id":"12D3KooWRDRzUdVGBWQr31vTjawwXZqsfgesLs9spWLSztDNHUp1","port":8302}}
Oct 22 18:03:36 ubuntu mina[721278]: {"timestamp":"2023-10-22 18:03:36.797831Z","level":"Debug","source":{"module":"Init__Mina_run","location":"File \"src/app/cli/src/init/mina_run.ml\", line 112, characters 10-22"},"message":"Could not visualize transition frontier since daemon is currently bootstrapping","metadata":{"coda_run":"Logging state before program ends","host":"5.180.186.25","peer_id":"12D3KooWRDRzUdVGBWQr31vTjawwXZqsfgesLs9spWLSztDNHUp1","port":8302}}
Oct 22 18:03:36 ubuntu mina[721278]: {"timestamp":"2023-10-22 18:03:36.797986Z","level":"Error","source":{"module":"Mina_net2","location":"File \"src/lib/mina_net2/mina_net2.ml\", line 189, characters 6-28"},"message":"Encountered $error while asking libp2p_helper for peers","metadata":{"error":{"commit_id":"55b78189c46e1811b8bdb78864cfa95409aeb96a","string":"helper process already exited (doing RPC ListPeers)"},"host":"5.180.186.25","peer_id":"12D3KooWRDRzUdVGBWQr31vTjawwXZqsfgesLs9spWLSztDNHUp1","port":8302}}
Oct 22 18:03:36 ubuntu mina[721278]:   ☠  Mina Daemon crashed.
Oct 22 18:03:36 ubuntu mina[721278]:    The Mina Protocol developers would like to know why!
Oct 22 18:03:36 ubuntu mina[721278]:     Please:
Oct 22 18:03:36 ubuntu mina[721278]:       Open an issue:
Oct 22 18:03:36 ubuntu mina[721278]:         <https://github.com/MinaProtocol/mina/issues/new>
Oct 22 18:03:36 ubuntu mina[721278]:       Briefly describe what you were doing and attach the crash report /root/.mina-config/coda_crash_report_2023-10-22_18-03-33.042861.tar.gz
Oct 22 18:03:36 ubuntu mina[721278]:
Oct 22 18:03:37 ubuntu systemd[2012]: mina.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 18:03:37 ubuntu systemd[2012]: mina.service: Failed with result 'exit-code'.
Oct 22 18:04:07 ubuntu systemd[2012]: mina.service: Scheduled restart job, restart counter is at 341.
Oct 22 18:04:07 ubuntu systemd[2012]: Stopped Mina Daemon Service.
Oct 22 18:04:07 ubuntu systemd[2012]: Started Mina Daemon Service.

### How frequently do you see this issue?

Frequently

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Error: Unable to connect to Mina daemon.
- The daemon might not be running. See logs (in `~/.mina-config/mina.log`) for details under the host:127.0.0.1.
  Run `mina daemon -help` to see how to start daemon.
- If you just started the daemon, wait a minute for the RPC server to start.
- Alternatively, the daemon may not be running the RPC server on (127.0.0.1 8301).
  If so, add flag `---daemon-port` with correct port when running this command.
```

### Additional information

[coda_crash_report_2023-10-22_18-03-33.042861.tar.gz](https://github.com/MinaProtocol/mina/files/13064144/coda_crash_report_2023-10-22_18-03-33.042861.tar.gz)

**Comment by shimkiv** [comment] 2023-10-23 07:07
Hey @thecoldblooded, thank you for reporting this. This issue is similar to https://github.com/MinaProtocol/mina/issues/14367.
It will be really helpful if you could run this Daemon version https://github.com/MinaProtocol/mina/releases/tag/2.0.0rampup6 for the time being and update this issue with additional crash report should you face it again. This will help us with issue triaging a lot. 
Thank you.

**Comment by shimkiv** [comment] 2023-10-23 07:07
Hey @thecoldblooded, thank you for reporting this. This issue is similar to https://github.com/MinaProtocol/mina/issues/14367.
It will be really helpful if you could run this Daemon version https://github.com/MinaProtocol/mina/releases/tag/2.0.0rampup6 for the time being and update this issue with additional crash report should you face it again. This will help us with issue triaging a lot. 
Thank you.

**Comment by thecoldblooded** [comment] 2023-10-23 08:01
> Hey @thecoldblooded, thank you for reporting this. This issue is similar to #14367. It will be really helpful if you could run this Daemon version https://github.com/MinaProtocol/mina/releases/tag/2.0.0rampup6 for the time being and update this issue with additional crash report should you face it again. This will help us with issue triaging a lot. Thank you.

thanks. now it works. 

```
Mina daemon status
-----------------------------------

Max observed block height:              1
Max observed unvalidated block height:  0
Local uptime:                           4m57s
Chain id:                               332c8cc05ba8de9efc23a011f57015d8c9ec96fac81d5d3f7a06969faf4bce92
Git SHA-1:                              4061884b18137c1182c7fcfa80f52804008a2509
Configuration directory:                /root/.mina-config/
Peers:                                  134
User_commands sent:                     0
SNARK worker:                           None
SNARK work fee:                         100000000
Sync status:                            Bootstrap
Block producers running:                1 (B62qnKexFyFub6M6mhT3Va3C5kEEUcajb33rzoNWzQasY81oGTSMV5p)
Coinbase receiver:                      Block producer
Consensus time now:                     epoch=0, slot=2718
Consensus mechanism:                    proof_of_stake
Consensus configuration:                
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2023-10-17 16:01:01.000000Z
        Acceptable network delay:  3m

Addresses and ports:                    
        External IP:    5.180.186.25
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWRDRzUdVGBWQr31vTjawwXZqsfgesLs9spWLSztDNHUp1
        Libp2p port:    8302
        Client port:    8301

Metrics:                                
        block_production_delay:             7 (0 0 0 0 0 0 0)
        transaction_pool_diff_received:     2
        transaction_pool_diff_broadcasted:  0
        transactions_added_to_pool:         0
        transaction_pool_size:              0
        snark_pool_diff_received:           0
        snark_pool_diff_broadcasted:        0
        pending_snark_work:                 0
        snark_pool_size:                    0
```

to make it clear, I have been running two nodes simultaneously. One is having this issue but the other one works smoothly. Is it mandatory to run this [Daemon version](https://github.com/MinaProtocol/mina/releases/tag/2.0.0rampup6) whether having issue or not? Do I need to update my working node or let it go?

**Comment by thecoldblooded** [comment] 2023-10-23 08:09
5 mins uptime loop and again crashed. 

```
Oct 23 08:07:59 ubuntu mina[1895270]: {"timestamp":"2023-10-23 08:07:59.724025Z","level":"Error","source":{"module":"Mina_net2","location":"File \"src/lib/mina_net2/mina_net2.ml\", line 189, characters 6-28"},"message":"Encountered $error while asking libp2p_helper for peers","metadata":{"error":{"commit_id":"4061884b18137c1182c7fcfa80f52804008a2509","string":"libp2p_helper process died before answering"},"host":"5.180.186.25","peer_id":"12D3KooWRDRzUdVGBWQr31vTjawwXZqsfgesLs9spWLSztDNHUp1","port":8302}}
Oct 23 08:08:02 ubuntu mina[1895270]: {"timestamp":"2023-10-23 08:08:02.851408Z","level":"Error","source":{"module":"Mina_net2","location":"File \"src/lib/mina_net2/mina_net2.ml\", line 189, characters 6-28"},"message":"Encountered $error while asking libp2p_helper for peers","metadata":{"error":{"commit_id":"4061884b18137c1182c7fcfa80f52804008a2509","string":"helper process already exited (doing RPC ListPeers)"},"host":"5.180.186.25","peer_id":"12D3KooWRDRzUdVGBWQr31vTjawwXZqsfgesLs9spWLSztDNHUp1","port":8302}}
Oct 23 08:08:03 ubuntu mina[1895270]:   ☠  Mina Daemon crashed.
Oct 23 08:08:03 ubuntu mina[1895270]:    The Mina Protocol developers would like to know why!
Oct 23 08:08:03 ubuntu mina[1895270]:     Please:
Oct 23 08:08:03 ubuntu mina[1895270]:       Open an issue:
Oct 23 08:08:03 ubuntu mina[1895270]:         <https://github.com/MinaProtocol/mina/issues/new>
Oct 23 08:08:03 ubuntu mina[1895270]:       Briefly describe what you were doing and attach the crash report /root/.mina-config/coda_crash_report_2023-10-23_08-07-59.729284.tar.gz
Oct 23 08:08:03 ubuntu mina[1895270]:     
Oct 23 08:08:03 ubuntu systemd[2012]: mina.service: Main process exited, code=exited, status=1/FAILURE
Oct 23 08:08:03 ubuntu systemd[2012]: mina.service: Failed with result 'exit-code'.
```

**Comment by shimkiv** [comment] 2023-10-23 13:04
So the latest version you mentioned in prev. message should allow us better understand the root cause of the problem that you initially were reporting.
Can you also attach new `2.0.0rampup6` crash report if any please?

**Comment by thecoldblooded** [comment] 2023-10-23 14:16
> So the latest version you mentioned in prev. message should allow us better understand the root cause of the problem that you initially were reporting. Can you also attach new `2.0.0rampup6` crash report if any please?

sure

[coda_crash_report_2023-10-23_14-07-04.491170.tar.gz](https://github.com/MinaProtocol/mina/files/13071624/coda_crash_report_2023-10-23_14-07-04.491170.tar.gz)

**Comment by shimkiv** [comment] 2023-10-23 14:53
@thecoldblooded thank you.
Just noticed that you're using `berkeley_seeds.txt` and curious which network you wold like to connect to? Is it `Berkeley` or `Testworld`?

**Comment by thecoldblooded** [comment] 2023-10-23 17:38
[coda_crash_report_2023-10-23_17-36-21.953495.tar.gz](https://github.com/MinaProtocol/mina/files/13074430/coda_crash_report_2023-10-23_17-36-21.953495.tar.gz)
again. crashed!

**Comment by thecoldblooded** [comment] 2023-10-24 12:20
@shimkiv any solution?

**Comment by shimkiv** [comment] 2023-10-24 13:53
Team is notified and investigation is in progress. Another issue you might want to check periodically is https://github.com/MinaProtocol/mina/issues/14367.

**Comment by thecoldblooded** [comment] 2023-10-29 19:18
> Team is notified and investigation is in progress. Another issue you might want to check periodically is #14367.

[coda_crash_report_2023-10-29_19-14-32.097325.tar.gz](https://github.com/MinaProtocol/mina/files/13199001/coda_crash_report_2023-10-29_19-14-32.097325.tar.gz)

I try to run mina with docker but getting error and crashed. could you check it? btw I know we have to run 2 nodes simultaneously and one is OK for now but this one is having issue and I could not solve it yet. Is it OK if I run just one node for now?

**Comment by deepthiskumar** [comment] 2023-11-02 01:28
> [coda_crash_report_2023-10-23_17-36-21.953495.tar.gz](https://github.com/MinaProtocol/mina/files/13074430/coda_crash_report_2023-10-23_17-36-21.953495.tar.gz)
again. crashed!

From the logs- the error is `no persistent root identifier found (should have been written already)`
This issue has already been raised here #14367 and is still under investigation

**Comment by deepthiskumar** [comment] 2023-11-02 01:33
>[coda_crash_report_2023-10-29_19-14-32.097325.tar.gz](https://github.com/MinaProtocol/mina/files/13199001/coda_crash_report_2023-10-29_19-14-32.097325.tar.gz)
I try to run mina with docker but getting error and crashed. could you check it? btw I know we have to run 2 nodes simultaneously and one is OK for now but this one is having issue and I could not solve it yet. Is it OK if I run just one node for now?

This seems like an issue with your key file, maybe corrupted. The daemon is not able to parse the keyfile.

**Comment by deepthiskumar** [comment] 2023-11-02 01:34
Duplicate of https://github.com/MinaProtocol/mina/issues/14367

**Closed by deepthiskumar** 2023-11-02 01:34 UTC
Labels: bug, triage, itn3, Testworld-2-0-protocol-performance-testing
