### ISSUE TITLE
Persistent frontier database crashes after reading Invalid_curve_point

### ISSUE THREAD

**Issue by codechallenge2019** [MinaProtocol/mina#7527] opened 2021-01-17 16:13 UTC
gcr.io/o1labs-192920/coda-daemon-baked:0.2.6-5c08d6d-5c08d6d-testworld-2258826 docker image crashed with the following log:
2021-01-17 09:42:45 UTC [Fatal] Unhandled top-level exception: $exn
 Generating crash report
       exn: {
   "sexp": [
     "monitor.ml.Error",
     [
       "Zexe_backend_common.Curve.Make(BaseField)(ScalarField)(Params)(C).Affine.Stable.V1.Invalid_curve_point(_)"
     ],
     [
       "Raised at file \"src/lib/zexe_backend/zexe_backend_common/curve.ml\", line 119, characters 47-76",
       "Called from file \"src/read.ml\", line 464, characters 18-42",
       "Called from file \"src/array.ml\" (inlined), line 6, characters 0-49",
       "Called from file \"src/std_internal.ml\" (inlined), line 97, characters 2-79",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 16, characters 6-65",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 16, characters 6-65",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 16, characters 6-65",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 16, characters 6-65",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 188, characters 8-96",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 188, characters 8-96",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 188, characters 8-96",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 188, characters 8-96",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 204, characters 10-63",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 203, characters 6-366",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 203, characters 6-366",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 203, characters 6-366",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 235, characters 10-63",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 234, characters 6-202",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 234, characters 6-202",
       "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 234, characters 6-202",
       "Called from file \"src/lib/zexe_backend/zexe_backend_common/plonk_dlog_proof.ml\", line 152, characters 8-298",
       "Called from file \"src/lib/zexe_backend/zexe_backend_common/plonk_dlog_proof.ml\", line 152, characters 8-298",
       "Called from file \"src/lib/allocation_functor/make.ml\", line 13, characters 34-61",
       "Called from file \"src/lib/pickles/proof.ml\", line 61, characters 12-41",
       "Called from file \"src/lib/pickles/proof.ml\" (inlined), line 42, characters 8-954",
       "Called from file \"src/lib/pickles/proof.ml\", line 42, characters 8-954",
       "Called from file \"src/lib/pickles/proof.ml\", line 42, characters 8-954",
       "Called from file \"src/lib/pickles/proof.ml\", line 164, characters 8-640",
       "Called from file \"src/lib/pickles/proof.ml\", line 164, characters 8-640",
       "Called from file \"src/utils.ml\", line 103, characters 49-76",
       "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 409, characters 6-87",
       "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 409, characters 6-87",
       "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 421, characters 50-74",
       "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 420, characters 4-144",
       "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 420, characters 4-144",
       "Called from file \"src/lib/ledger_proof/ledger_proof.ml\", line 13, characters 6-79",
       "Called from file \"src/lib/ledger_proof/ledger_proof.ml\", line 13, characters 6-79",
       "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 38-45",
       "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 4-98",
       "Called from file \"src/lib/one_or_two/one_or_two.ml\" (inlined), line 7, characters 4-98",
       "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 4-98",
       "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 4-98",
       "Called from file \"src/lib/transaction_snark_work/transaction_snark_work.ml\", line 82, characters 10-75",
       "Called from file \"src/lib/transaction_snark_work/transaction_snark_work.ml\", line 80, characters 6-197",
       "Called from file \"src/lib/transaction_snark_work/transaction_snark_work.ml\", line 80, characters 6-197",
       "Called from file \"src/read.ml\", line 401, characters 23-47",
       "Called from file \"src/read.ml\" (inlined), line 407, characters 16-64",
       "Called from file \"src/list0.ml\" (inlined), line 6, characters 0-48",
       "Called from file \"src/std_internal.ml\" (inlined), line 105, characters 2-83",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 82, characters 10-44",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\" (inlined), line 81, characters 6-302",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 81, characters 6-302",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 81, characters 6-302",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 133, characters 6-185",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 133, characters 6-185",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 172, characters 8-118",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 171, characters 6-165",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 171, characters 6-165",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 188, characters 14-36",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 188, characters 4-63",
       "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 188, characters 4-63",
       "Called from file \"src/lib/mina_transition/external_transition.ml\", line 34, characters 10-70",
       "Called from file \"src/lib/mina_transition/external_transition.ml\", line 31, characters 6-540",
       "Called from file \"src/lib/mina_transition/external_transition.ml\", line 31, characters 6-540",
       "Called from file \"src/lib/allocation_functor/make.ml\", line 13, characters 34-61",
       "Called from file \"src/option.ml\", line 183, characters 23-28",
       "Called from file \"src/lib/transition_frontier/persistent_frontier/database.ml\" (inlined), line 215, characters 33-46",
       "Called from file \"src/lib/transition_frontier/persistent_frontier/database.ml\", line 311, characters 6-46",
       "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 109, characters 12-41",
       "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 142, characters 22-39",
       "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 168, characters 26-46",
       "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 152, characters 24-32",
       "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
       "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
       "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
       "Caught by monitor coda"
     ]
   ],
   "backtrace": [
     "Raised at file \"src/lib/zexe_backend/zexe_backend_common/curve.ml\", line 119, characters 47-76",
     "Called from file \"src/read.ml\", line 464, characters 18-42",
     "Called from file \"src/array.ml\" (inlined), line 6, characters 0-49",
     "Called from file \"src/std_internal.ml\" (inlined), line 97, characters 2-79",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 16, characters 6-65",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 16, characters 6-65",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 16, characters 6-65",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 16, characters 6-65",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 188, characters 8-96",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 188, characters 8-96",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 188, characters 8-96",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 188, characters 8-96",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 204, characters 10-63",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 203, characters 6-366",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 203, characters 6-366",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 203, characters 6-366",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 235, characters 10-63",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\" (inlined), line 234, characters 6-202",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 234, characters 6-202",
     "Called from file \"src/lib/pickles_types/dlog_plonk_types.ml\", line 234, characters 6-202",
     "Called from file \"src/lib/zexe_backend/zexe_backend_common/plonk_dlog_proof.ml\", line 152, characters 8-298",
     "Called from file \"src/lib/zexe_backend/zexe_backend_common/plonk_dlog_proof.ml\", line 152, characters 8-298",
     "Called from file \"src/lib/allocation_functor/make.ml\", line 13, characters 34-61",
     "Called from file \"src/lib/pickles/proof.ml\", line 61, characters 12-41",
     "Called from file \"src/lib/pickles/proof.ml\" (inlined), line 42, characters 8-954",
     "Called from file \"src/lib/pickles/proof.ml\", line 42, characters 8-954",
     "Called from file \"src/lib/pickles/proof.ml\", line 42, characters 8-954",
     "Called from file \"src/lib/pickles/proof.ml\", line 164, characters 8-640",
     "Called from file \"src/lib/pickles/proof.ml\", line 164, characters 8-640",
     "Called from file \"src/utils.ml\", line 103, characters 49-76",
     "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 409, characters 6-87",
     "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 409, characters 6-87",
     "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 421, characters 50-74",
     "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 420, characters 4-144",
     "Called from file \"src/lib/transaction_snark/transaction_snark.ml\", line 420, characters 4-144",
     "Called from file \"src/lib/ledger_proof/ledger_proof.ml\", line 13, characters 6-79",
     "Called from file \"src/lib/ledger_proof/ledger_proof.ml\", line 13, characters 6-79",
     "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 38-45",
     "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 4-98",
     "Called from file \"src/lib/one_or_two/one_or_two.ml\" (inlined), line 7, characters 4-98",
     "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 4-98",
     "Called from file \"src/lib/one_or_two/one_or_two.ml\", line 7, characters 4-98",
     "Called from file \"src/lib/transaction_snark_work/transaction_snark_work.ml\", line 82, characters 10-75",
     "Called from file \"src/lib/transaction_snark_work/transaction_snark_work.ml\", line 80, characters 6-197",
     "Called from file \"src/lib/transaction_snark_work/transaction_snark_work.ml\", line 80, characters 6-197",
     "Called from file \"src/read.ml\", line 401, characters 23-47",
     "Called from file \"src/read.ml\" (inlined), line 407, characters 16-64",
     "Called from file \"src/list0.ml\" (inlined), line 6, characters 0-48",
     "Called from file \"src/std_internal.ml\" (inlined), line 105, characters 2-83",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 82, characters 10-44",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\" (inlined), line 81, characters 6-302",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 81, characters 6-302",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 81, characters 6-302",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 133, characters 6-185",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 133, characters 6-185",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 172, characters 8-118",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 171, characters 6-165",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 171, characters 6-165",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 188, characters 14-36",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 188, characters 4-63",
     "Called from file \"src/lib/staged_ledger_diff/staged_ledger_diff.ml\", line 188, characters 4-63",
     "Called from file \"src/lib/mina_transition/external_transition.ml\", line 34, characters 10-70",
     "Called from file \"src/lib/mina_transition/external_transition.ml\", line 31, characters 6-540",
     "Called from file \"src/lib/mina_transition/external_transition.ml\", line 31, characters 6-540",
     "Called from file \"src/lib/allocation_functor/make.ml\", line 13, characters 34-61",
     "Called from file \"src/option.ml\", line 183, characters 23-28",
     "Called from file \"src/lib/transition_frontier/persistent_frontier/database.ml\" (inlined), line 215, characters 33-46",
     "Called from file \"src/lib/transition_frontier/persistent_frontier/database.ml\", line 311, characters 6-46",
     "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 109, characters 12-41",
     "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 142, characters 22-39",
     "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 168, characters 26-46",
     "Called from file \"src/lib/transition_frontier/persistent_frontier/worker.ml\", line 152, characters 24-32",
     "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
     "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
     "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
   ]
 }

**Comment by auruhm** [comment] 2021-01-17 18:39
Guys, I have the same. Coda demon crashed!!

**Comment by mrmr1993** [comment] 2021-02-02 10:22
This is most likely caused by an invalid public key being included in a fee transfer or coinbases. We have #7666 to fix that issue, so I'm optimistically setting this to close when that PR is merged.

**Closed** 2021-02-02 20:32 UTC
Labels: Impact:  Medium, Risk: Low
