### ISSUE TITLE
Daemon crash

### ISSUE THREAD

**Issue by trader-payne** [MinaProtocol/mina#6063] opened 2020-09-20 16:42 UTC
[coda_crash_report_2020-09-20_16-06-43.561801.tar.gz](https://github.com/CodaProtocol/coda/files/5252095/coda_crash_report_2020-09-20_16-06-43.561801.tar.gz)

**Comment by garethtdavies** [comment] 2020-09-21 01:23
This is the `write to closed pipe` error and duplicate of #6049

**Comment by mrmr1993** [comment] 2020-10-13 00:58
Closing, this was fixed in #6357.

**Closed by mrmr1993** 2020-10-13 00:58 UTC
