### ISSUE TITLE
Check that archive node deb package works as expected

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5565] opened 2020-08-04 20:30 UTC
The only change that should be required here is that the archive node deb should list postgresql as a dependency.

**Comment by robinbb** [comment] 2022-10-13 15:17
@lk86 I wonder if @kaozenn can take this from you?

**Comment by mzajda0mina** [comment] 2022-11-09 09:36
relates to #11976 specific for nix deb package

**Comment by robinbb** [comment] 2022-11-10 07:36
@mzajda0mina Why is this issue marked "Archived in project"? Is it done?

**Comment by mzajda0mina** [comment] 2022-11-10 15:27
@robinbb is a duplicate of #11976

**Comment by mzajda0mina** [comment] 2022-11-10 18:50
@robinbb hm, yes, I was not correct re the duplicate ticket number. I did it during standup, where a duplicate was pointed to me, but now I don't see it... I will re-check. I see also that I added the [nix-dep] prefix in the title. It means that it depends on NIX work. If we get NIX working the issue doesn't exist. The title is misleading, too. It's about PostgreSQL dependency and not  Archive node working state.
 
Re the archiving non-closed issue: it was my way to remove it from this dashboard and don't lose it forever. When I have better grip on the project I intend to move or delete non issues.

**Comment by robinbb** [comment] 2022-11-10 19:20
So, unless there is a duplicate issue identified, we should not archive this one because we might then lose track of it. If a duplicate issue is identified, we can close this one and mark it "Done".

**Closed** 2023-03-29 18:49 UTC
Labels: archive-node
