### ISSUE TITLE
Parent directory /Users/xxxx/keys does not exist

### ISSUE THREAD

**Issue by ghisooo** [MinaProtocol/mina#12787] opened 2023-03-07 18:33 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

I'm using my Macbook pro(m2 chip in it) and docker to run a node.
I followed the instruction on Mina-protocol webpage, but it isn't working as expected. (I already changed directory and files' access permissions via chmod command.)

```
...
[ERROR] Entrypoint script /entrypoint.d/. is not a regular file, ignoring
[ERROR] Entrypoint script /entrypoint.d/.. is not a regular file, ignoring
2023-03-07 18:28:08 UTC [Info] Mina daemon is booting up; built with commit "25388a0fed9695e8e9d04f75f50c2bae1c9c80db" on branch "master"
2023-03-07 18:28:08 UTC [Info] Created daemon lockfile "/root/.mina-config/.mina-lock"
2023-03-07 18:28:08 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"
2023-03-07 18:28:08 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2023-03-07 18:28:08 UTC [Info] Booting may take several seconds, please wait
2023-03-07 18:28:08 UTC [Info] Reading configuration files $config_files
	config_files: [ "/var/lib/coda/config_25388a0f.json", "/root/.mina-config/daemon.json" ]
2023-03-07 18:28:08 UTC [Warn] Could not read configuration from "/root/.mina-config/daemon.json"
2023-03-07 18:28:08 UTC [Info] Initializing with runtime configuration. Ledger name: "mainnet"
2023-03-07 18:28:08 UTC [Info] Using the compiled constraint constants
2023-03-07 18:28:09 UTC [Info] Loaded genesis ledger from $ledger_file
	ledger_file: "/root/.mina-config/genesis/genesis_ledger_accounts_71d4f4a0e8c1f3e78760b989234760584969ea0144ed1a3057234f6f0e73621a.tar.gz"
Using block producer keypair private-key password from environment variable MINA_PRIVKEY_PASS

FATAL ERROR

  ☠  Mina Daemon encountered a configuration error loading block producer keypair.

Parent directory /Users/xxxx/keys does not exist

Hint: mkdir -p /Users/xxxx/keys; chmod 700 /Users/georgek/keys

Mina process exited with status code 1
```

### Steps to Reproduce

After generating a key, I followed the following page.
[2. Created mina-env, and mina-config](https://docs.minaprotocol.com/node-operators/connecting-to-the-network)

### Expected Result

A node is running.

### Actual Result

[mina.log](https://github.com/MinaProtocol/mina/files/10912808/mina.log)

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Nothing.
```

**Comment by vanarasiantonyswamy** [comment] 2023-03-14 23:49
Could repro the issue on Mac M1.

**Comment by vanarasiantonyswamy** [comment] 2023-03-17 03:43
Currently similar issue is tracked as part of https://github.com/MinaProtocol/mina/issues/12089 where we are working on Mina Docker Container to run natively on CPU architecture.

**Comment by vanarasiantonyswamy** [comment] 2023-03-20 20:27
duplicate of https://github.com/MinaProtocol/mina/issues/12089.

**Closed** 2023-03-20 20:26 UTC
Labels: bug, triage
