### ISSUE TITLE
mina crashing when trying to synchronize

### ISSUE THREAD

**Issue by mnguyen-io** [MinaProtocol/mina#7374] opened 2021-01-08 01:01 UTC
Trying to start coda/mina daemon for the first time - this happens while its attempting to sync.

command:

/usr/local/bin/coda daemon   -peer-list-file /home/mina/mina_work/peers.txt  -generate-genesis-proof true   -log-level Debug

Last few log lines with Debug logging enabled:
```
  {
    "payload": {
      "common": {
        "fee": "0.099463309",
        "fee_token": "1",
        "fee_payer_pk":
          "B62qisP6CjtmVugadA2RfNfXBznGnZTKKwusXcATwuEkm8yLSmajszA",
        "nonce": "108",
        "valid_until": "4294967295",
        "memo": "E4Yd67s51QN9DZVDy8JKPEoNGykMsYQ5KRiKpZHiLZTjA8dB9SnFT"
      },
      "body": [
        "Payment",
        {
          "source_pk":
            "B62qisP6CjtmVugadA2RfNfXBznGnZTKKwusXcATwuEkm8yLSmajszA",
          "receiver_pk":
            "B62qnbskrh5TMZKA6jzTpLxWHjjRCS8pdayJtmc5YbReTCGXm5BpJt2",
          "token_id": "1",
          "amount": "1500000"
        }
      ]
    },
    "signer": "B62qisP6CjtmVugadA2RfNfXBznGnZTKKwusXcATwuEkm8yLSmajszA",
    "signature":
      "7mXTKQfnzpNZr37kX3rjSPyKMNzh4A68DMxve6JBDYdtRA7j3M8aJHq1wM8fk7Aeerx8DXHavgDWYkFU4idVvi6SPSWzko3L"
  }
]
2021-01-08 00:55:21 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "sexp": [
    "Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"bf0c1ef4-64cf-3559-0f20-36353122d54d\", \"File \\\"src/lib/transition_router/transition_router.ml\\\", line 508, characters 61-68\")"
  ],
  "backtrace": [
    "Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57",
    "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 121, characters 6-26",
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1189, characters 29-65",
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1202, characters 18-30",
    "Called from file \"src/lib/network_pool/network_pool_base.ml\", line 101, characters 15-67",
    "Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 155, characters 28-37",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2021-01-08 00:55:21 UTC [Debug] Successfully wrote the visualization of the registered masks at location: /root/.coda-config/coda_crash_report_2021-01-08_00-55-21.968267/registered_masks.dot.
2021-01-08 00:55:22 UTC [Debug] Could not visualize transition frontier since daemon is currently bootstrapping


  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2021-01-08_00-55-21.968267.tar.gz

```

**Comment by mnguyen-io** [comment] 2021-01-08 03:21
This may be a memory issue. Original VM I ran this on had 16GB of RAM. I've spun up an instance with 64GB and it hasn't crashed yet.

Memory usage has exceeded 16GB already and I have nothing else installed - Fresh Ubuntu installation.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6149 mina      20   0 12.890g 0.011t  65460 R  82.4 18.5  26:19.93 coda
 6471 mina      20   0 5328276 2.407g  29996 S  31.9  3.8   3:23.82 coda-libp2p_hel
 6403 mina      20   0 2629344 2.136g  63740 S   0.0  3.4   4:01.73 exe
 7147 mina      20   0  487136 176820  64016 S 539.9  0.3   0:30.43 exe

mina@instance-1:~/.coda-config$ free -m
              total        used        free      shared  buff/cache   available
Mem:          64324       16989       43664          12        3670       48083
Swap:             0           0           0

**Comment by mnguyen-io** [comment] 2021-01-08 03:38
Nevermind - adding more memory only seemed to allow it to run a bit longer.

The process eventually segfaulted after exceeding 20 GB of memory. I didn't get the exact amount of memory that was used as it died before I could check:

mina@instance-1:~/.coda-config$ free -m
              total        used        free      shared  buff/cache   available
Mem:          64324       20407       40213          12        3703       44834
Swap:             0           0           0
mina@instance-1:~/.coda-config$ coda client status
{"timestamp":"2021-01-08 03:30:36.599258Z","level":"Debug","source":{"module":"Block_time","location":"File \"src/lib/block_time/block_time.ml\", line 76, characters 18-30"},"message":"Environment variable CODA_TIME_OFFSET not found, using default of 0","metadata":{"pid":7285}}
Coda daemon status
-----------------------------------

Global number of accounts:                     2687
Block height:                                  425
Max observed block length:                     723
Local uptime:                                  41m36s
Ledger Merkle root:                            jwR2Vj9bZmEoVtMbSrFej8PfNBW8QF4FXpPm5gunryw4nX771z8
Protocol state hash:                           3NKHWD1gj8vCpJ5kopzNDQjpmpiR2LCJ4M6Cz3qt2NC5Q2rfjzAq
Chain id:                                      2dbac725ebb5c6c8b1daf21cda9e3694951ab72afe9be99ff7ca47574112f43b
Git SHA-1:                                     [DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af
Configuration directory:                       /home/mina/.coda-config
Peers:                                         57 (34.123.64.160:10511 34.68.112.47:10506 135.181.146.223:8302 193.35.56.234:8302 149.74.248.92:8302 63.250.54.209:8302 45.77.24.247:8302 35.223.31.24:8302 47.253.32.138:8302 35.193.85.23:8302 139.162.2.202:8302 35.238.10.172:10510 161.97.143.67:8302 135.181.115.43:8302 135.181.5.54:8302 34.66.157.200:10001 92.53.84.132:8302 35.184.213.234:10519 212.71.247.49:8302 110.234.31.118:8302 35.238.126.24:8302 45.56.106.197:8302 35.238.143.228:8302 94.130.206.245:8302 35.223.59.114:10504 34.70.132.136:10516 135.181.180.250:8302 135.181.111.9:8302 144.76.203.231:8302 146.148.101.167:10513 95.217.88.206:8302 135.181.164.212:8302 95.217.152.6:8302 5.9.121.47:8302 95.165.157.171:8302 139.64.165.224:8302 35.226.95.52:10502 94.130.164.60:8302 161.97.113.100:8302 45.32.133.94:8302 49.50.163.98:8302 188.124.36.224:8302 34.123.174.31:10001 45.79.115.226:8302 95.216.214.178:8302 34.66.76.119:10501 62.171.154.207:8302 45.56.127.197:8302 45.125.239.157:8302 173.255.211.157:8302 159.146.54.127:8302 95.216.5.230:8302 168.119.140.226:8302 34.72.112.110:10909 35.202.60.48:8302 35.193.232.146:8302 95.217.134.63:8302)
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                25000000
Sync status:                                   Catchup
Block producers running:                       0
Best tip consensus time:                       epoch=0, slot=2253
Best tip global slot (across all hard-forks):  2253
Next block will be produced in:                None this epoch… checking at in 6.53d
Consensus time now:                            epoch=0, slot=4005
Consensus mechanism:                           proof_of_stake
Consensus configuration:
	Delta:                     0
	k:                         290
	Slots per epoch:           7140
	Slot duration:             3m
	Epoch duration:            14d21h
	Chain start timestamp:     2020-12-30 19:14:30.000000Z
	Acceptable network delay:  3m

Addresses and ports:
	External IP:    34.95.44.129
	Bind IP:        0.0.0.0
	Libp2p PeerID:  12D3KooWKPMJBc5AiJKbU3bXiDMfrDYkhceFKnTF3cXid6vdMuKq
	Libp2p port:    8302
	Client port:    8301


2021-01-08 03:31:29 UTC [Info] Catch up to $target_hash
	target_hash: "3NLWJGffCdRGCNe6fw15T6nGLtWe1id9ZQMcU8sYpHmYfARqWrfU"
2021-01-08 03:31:29 UTC [Info] Coda daemon is doing ledger catchup
2021-01-08 03:32:05 UTC [Warn] RPC call error for "get_transition_chain"
2021-01-08 03:32:05 UTC [Warn] RPC call error for "get_transition_chain"
2021-01-08 03:32:05 UTC [Warn] RPC call error for "get_transition_chain"
2021-01-08 03:32:07 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $error
	error: {
  "string":
    "RPC #20980 failed: \"internal RPC error error: unknown stream_idx\""
}
2021-01-08 03:32:09 UTC [Error] error sending message on stream 8819: $error
	error: {
  "string":
    "RPC #21001 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: closed stream\""
}
2021-01-08 03:32:09 UTC [Warn] RPC call error for "get_transition_chain"
2021-01-08 03:32:09 UTC [Error] error sending message on stream 8822: $error
	error: {
  "string":
    "RPC #21016 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: closed stream\""
}
2021-01-08 03:32:09 UTC [Warn] RPC call error for "get_transition_chain"
2021-01-08 03:32:10 UTC [Error] error sending message on stream 8819: $error
	error: {
  "string":
    "RPC #21047 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: closed stream\""
}
2021-01-08 03:32:10 UTC [Error] error sending message on stream 8822: $error
	error: {
  "string":
    "RPC #21061 failed: \"only wrote 0 out of 698 bytes error: libp2p error error: closed stream\""
}
2021-01-08 03:32:45 UTC [Warn] RPC call error for "get_transition_chain"
2021-01-08 03:32:45 UTC [Warn] RPC call error for "get_transition_chain"
2021-01-08 03:32:53 UTC [Info] Sending transition_chain to $peer
	peer: {
  "host": "63.250.54.209",
  "peer_id": "12D3KooWJXFVTDQQuHgZCC2y6z4UQ84y8QvGBSm2oEfS2fc2HASv",
  "libp2p_port": 8302
}
Segmentation fault (core dumped)
mina@instance-1:~/mina_work$

**Comment by mrmr1993** [comment] 2021-01-08 12:56
This is a duplicate of #6949. Closing.

The segfault issue is being tracked in #7333.

**Closed by mrmr1993** 2021-01-08 12:56 UTC
