### ISSUE TITLE
Some of our nodes getting stuck in Synced at a lower block height than the consensus one

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7555] opened 2021-01-20 17:36 UTC
archive-node-7ff556cd59-7dz5d 	 Synced 	 8h1m44s 	 2726 	 8
	 fish-block-producer-1-6bb9c867cf-bsbn7 	 Catchup 	 12h25m36s 	 2615 	 111
	 fish-block-producer-2-774c99f777-jdm6k 	 Synced 	 7h44m13s 	 2726 	 97
	 fish-block-producer-3-74458dbd99-489r9 	 Bootstrap 	 6m56s 	 _____ 	 24
	 fish-block-producer-4-8487f5b74f-qrxpf 	 Synced 	 4h39m49s 	 2726 	 89
	 fish-block-producer-5-68968d9598-v89gb 	 Synced 	 3h32m42s 	 2726 	 75
	 seed-node-5577c575bf-9t575 	 Synced 	 7h57m6s 	 2723 	 1181
	 snark-coordinator-jwpmmu-59d988cbd5-7m8g4 	 Synced 	 6h16m28s 	 2726 	 13
	 whale-block-producer-10-7474478bcf-nrsr4 	 Catchup 	 17m28s 	 2638 	 22
	 whale-block-producer-11-7845f78c5b-j7q9s 	 Synced 	 7h7m15s 	 2726 	 95
	 whale-block-producer-12-6cc4469896-5v956 	 Synced 	 4h49m54s 	 2726 	 79
	 whale-block-producer-13-db87558db-9npxp 	 Synced 	 4h51m26s 	 2726 	 93
	 whale-block-producer-14-7d99bcd69c-5z8mh 	 Synced 	 4h6m38s 	 2726 	 76
	 whale-block-producer-15-86754b4f56-9zqkj 	 Synced 	 8h35m43s 	 2726 	 90
	 whale-block-producer-2-5bbdd4bb68-5hk5l 	 Synced 	 18h56m19s 	 2678 	 115
	 whale-block-producer-3-75b9cd8578-897lb 	 Bootstrap 	 10m54s 	 _____ 	 23
	 whale-block-producer-4-746f75ff66-jmjd6 	 Catchup 	 51m37s 	 2685 	 22
	 whale-block-producer-5-65597458d8-8pqwf 	 Catchup 	 19m58s 	 2475 	 9
	 whale-block-producer-6-54f684ccf7-flcg5 	 Bootstrap 	 1m12s 	 _____ 	 7
	 whale-block-producer-7-78c95fc454-2hvl6 	 Synced 	 10h3m25s 	 2726 	 113
	 whale-block-producer-8-d4946b947-jhtc4 	 Synced 	 19h52m31s 	 2726 	 145
	 whale-block-producer-9-7bf94fd76-bfsjl 	 Synced 	 22h16m18s 	 2684 	 166

**Comment by raghulraj** [comment] 2021-01-25 20:54
As the logs are big, sharing it via gdrive
https://drive.google.com/file/d/1zjT4olHHJw9vOTpIgx1ECwLdtNPnHYVh/view?usp=sharing

**Comment by aneesharaines** [comment] 2021-02-09 22:21
Same issue as #7750 and #7749?

**Comment by Igor-Tselkovskiy** [comment] 2021-02-10 04:45
The same #7855

**Comment by Igor-Tselkovskiy** [comment] 2021-02-22 00:52
[mina-rejected-blocks.log](https://github.com/MinaProtocol/mina/files/6018950/mina-rejected-blocks.log)

**Comment by lampardlb** [comment] 2021-02-22 07:39
I encountered the same issue on Zenith testnet. Screenshot and log attached. Hope they help
<img width="794" alt="Screenshot 2021-02-22 at 13 11 33" src="https://user-images.githubusercontent.com/1702296/108676712-9a6be700-7523-11eb-8eab-13faa93234b6.png">

[mina-rejected-blocks.log](https://github.com/MinaProtocol/mina/files/6020216/mina-rejected-blocks.log)

**Comment by deepthiskumar** [comment] 2021-02-22 22:05
Not many blocks in the rejected-blocks log, especially none in the range `max observed block height` to `max observed unvalidated block height`. So seems like they all passed initial validation.

**Comment by lampardlb** [comment] 2021-02-22 23:00
Thanks @deepthiskumar . Sorry I don't have enough technical understanding on this. I should add that I produced 3 orphaned blocks in a row with wrong heights when the server lost track of the correct height.

**Comment by Igor-Tselkovskiy** [comment] 2021-02-22 23:19
> Not many blocks in the rejected-blocks log, especially none in the range `max observed block height` to `max observed unvalidated block height`. So seems like they all passed initial validation.

![image](https://user-images.githubusercontent.com/57884194/108782854-6a513200-757d-11eb-9e60-04ee9b2dfe8e.png)
Not a lot, but still the height is not resynchronized any further. Noda froze because she thinks she is on the right branch.

**Comment by deepthiskumar** [comment] 2021-02-22 23:30
@Igor-Tselkovskiy Could you export your logs using `coda client export-logs` command and share the link please?

**Comment by deepthiskumar** [comment] 2021-02-22 23:36
> Thanks @deepthiskumar . Sorry I don't have enough technical understanding on this. I should add that I produced 3 orphaned blocks in a row with wrong heights when the server lost track of the correct height.

No worries.  These blocks passed initial set of validations but were dropped later on and we might find some logs on that in coda.log files. If you haven't restarted your node then exporting the logs using `coda client export-logs` command and sharing the link here would be helpful.

**Comment by Igor-Tselkovskiy** [comment] 2021-02-22 23:37
https://disk.yandex.ru/d/51rT-z4BPFgfNw 

Please note - many users, if they see this error, simply restart the node ...

**Comment by Igor-Tselkovskiy** [comment] 2021-02-22 23:37
> @Igor-Tselkovskiy Could you export your logs using `coda client export-logs` command and share the link please?

https://disk.yandex.ru/d/51rT-z4BPFgfNw

Please note - many users, if they see this error, simply restart the node ...

**Comment by lampardlb** [comment] 2021-02-23 02:44
> > Thanks @deepthiskumar . Sorry I don't have enough technical understanding on this. I should add that I produced 3 orphaned blocks in a row with wrong heights when the server lost track of the correct height.
> 
> No worries. These blocks passed initial set of validations but were dropped later on and we might find some logs on that in coda.log files. If you haven't restarted your node then exporting the logs using `coda client export-logs` command and sharing the link here would be helpful.

Sure. Here it is: https://1drv.ms/u/s!AlOGZ7BQqAI1iKlfKZCIYqxMVpHZmg?e=xd6fdy

**Comment by ghost-not-in-the-shell** [comment] 2021-02-23 22:21
This issue seems to be caused by nodes are silently dropping blocks because libp2p validation expired after 5 min.

**Comment by mrmr1993** [comment] 2021-03-18 02:47
Since I don't see it documented anywhere: we expect that #8196 should fix this, and are currently testing it to make sure that it doesn't cause any other issues.

**Comment by codechallenge2019** [comment] 2021-04-01 03:57
My node constantly sticks after 2-3 days of uptime.
I see in logs the following:
[Error] Dropping blocks because libp2p validation expired

**Comment by pkrasam** [comment] 2021-04-12 02:15
Is there a permanent fix for this error?
```
Dropping blocks because libp2p validation expired
```

**Comment by mrmr1993** [comment] 2021-04-12 02:44
> Is there a permanent fix for this error?

I'm hopeful that #8506 will fix the remaining cases that we had overlooked. We're currently testing a version of this on the devnet seed nodes, with the aim of including it in the next release.

**Comment by hsq125** [comment] 2021-04-26 11:30
Node stuck after 3 days as well.

```
Max observed block height:                     13547
Max observed unvalidated block height:         13786
```

I also have these lines in the log

```
2021-04-26 11:23:54 UTC [Warn] validation callback timed out before we could respond
2021-04-26 11:23:54 UTC [Error] Dropping blocks because libp2p validation expired
```

Version is `1.1.5-a42bdee`

Remark : CPU activity dropped from 70% to 20%. No more mina-helper process alive anymore.

**Comment by imeckler** [comment] 2021-05-31 15:06
We're still seeing this on `baffb589965aa0a8552dca15e209d2a011af3d21`. @bkase and I noticed that the node that got stuck had a single `mina parallel-worker` process whereas the ones that were not stuck had 2. Hypothesis is the verifier process is dying and not getting restarted properly.

**Comment by hsq125** [comment] 2021-06-09 19:29
Ohter point that maybe relevant for investigation : it does not only happen after 2-3 days. I caught one of my nodes logging this kind of error **after 50 minutes**.

- The daemon was started at 2021-06-09 18:15:17 UTC
- The first message indicating such expiration' came at 2021-06-09 19:09:51 UTC

`2021-06-09 19:09:51 UTC [Error] Dropping blocks because libp2p validation expired`

**Comment by hsq125** [comment] 2021-06-09 19:40
> We're still seeing this on `baffb589965aa0a8552dca15e209d2a011af3d21`. @bkase and I noticed that the node that got stuck had a single `mina parallel-worker` process whereas the ones that were not stuck had 2. Hypothesis is the verifier process is dying and not getting restarted properly.
> 
> Anyone debugging should look at seed 5 on 5/13 between 8:07-8:11 PT. It received a block around 8:07 and accepted it, and then at 8:11 failed to accept a block which all other nodes accepted.

I confirm this. I noticed that several times.

**Comment by hsq125** [comment] 2021-06-09 19:45
> Node stuck after 3 days as well.
> 
> ```
> Max observed block height:                     13547
> Max observed unvalidated block height:         13786
> ```
> 
> I also have these lines in the log
> 
> ```
> 2021-04-26 11:23:54 UTC [Warn] validation callback timed out before we could respond
> 2021-04-26 11:23:54 UTC [Error] Dropping blocks because libp2p validation expired
> ```
> 
> Version is `1.1.5-a42bdee`
> 
> Remark : CPU activity dropped from 70% to 20%. No more mina-helper process alive anymore.

I confirm this. I noticed it several times.

**Comment by c29r3** [comment] 2021-06-10 04:45
I wrote a script that reloads a node `if highest_unvalidated_block_length_received - blockchain_length > 3` and send logs via telegram (last 40 minutes)
`Git SHA-1: a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a`
[mina_log.txt](https://github.com/MinaProtocol/mina/files/6628384/mina_log.txt)
![image](https://user-images.githubusercontent.com/52304443/121466221-bb1b5800-c9bf-11eb-8fd2-cdb67c8bc251.png)

**Closed** 2024-02-02 01:37 UTC
Labels: investigation, Impact:  High
