### ISSUE TITLE
Nodes that are peered directly with collect peers above the 50 cap (hundreds)

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7295] opened 2021-01-01 19:15 UTC

**Comment by es92** [comment] 2021-01-01 20:42
This may be related to the other issue seen here, as we're noticing that issue only on our nodes but not the community nodes: https://github.com/MinaProtocol/mina/issues/7294

**Comment by aneesharaines** [comment] 2021-01-05 22:05
Elizabeth is investigating why we aren't respecting the max.  Also need another set of eyes.

**Comment by bkase** [comment] 2021-01-11 18:36
I'm closing this as a dupe of the (slightly more detailed) #7421

**Closed by bkase** 2021-01-11 18:36 UTC
Labels: P0
