### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by lyubo-damyanov** [MinaProtocol/mina#7158] opened 2020-12-21 02:14 UTC
Hi, I tried to run a node with my original keypair (public key: B62qs2afaLmyxCYHHqQtQpYHHEX4qzNu9FyKG2zUveFBnJv36Nvhbj3 , issued before the fork, my 66000 stake is there) but it produced this error. I had removed .coda-config folder as per the instructions in the Hard Fork document and had followed precisely the instructions in the Connect to the Network article. Coda version is correct.
[coda_crash_report_2020-12-21_01-56-03.661828.tar.gz](https://github.com/MinaProtocol/mina/files/5721961/coda_crash_report_2020-12-21_01-56-03.661828.tar.gz)
<img width="960" alt="Screenshot 2020-12-21 040943" src="https://user-images.githubusercontent.com/73860692/102732204-c19b1200-4342-11eb-9d00-eb61f7ec3337.png">

**Comment by garethtdavies** [comment] 2020-12-21 15:53
`Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference` is duplicate of #6357

**Comment by mrmr1993** [comment] 2021-01-08 13:02
Closing as a duplicate of #6949.

**Closed by mrmr1993** 2021-01-08 13:02 UTC
