### ISSUE TITLE
Coda crush

### ISSUE THREAD

**Issue by bgpntx** [MinaProtocol/mina#7349] opened 2021-01-06 14:53 UTC
Hi, coda crushed with snark worker running. 
Please find report attached.

Thanks!

[coda_crash_report_2021-01-06_14-22-03.199006.tar.gz](https://github.com/MinaProtocol/mina/files/5776398/coda_crash_report_2021-01-06_14-22-03.199006.tar.gz)

**Comment by ghost-not-in-the-shell** [comment] 2021-01-07 19:16
This crash is caused by dangling_mask_reference

**Comment by mrmr1993** [comment] 2021-01-08 13:00
```json
{
  "timestamp": "2021-01-06 14:22:02.937533Z",
  "level": "Fatal",
  "source": {
    "module": "Init__Coda_run",
    "location": "File \"src/app/cli/src/init/coda_run.ml\", line 564, characters 2-26"
  },
  "message": "Unhandled top-level exception: $exn\nGenerating crash report",
  "metadata": {
    "exn": {
      "sexp": [
        "Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"20022a59-942b-39d8-bc7d-615a436d1340\", \"File \\\"src/lib/transition_router/transition_router.ml\\\", line 508, characters 61-68\")"
      ],
      "backtrace": [
        "Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57",
        "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 121, characters 6-26",
        "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1189, characters 29-65",
        "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1202, characters 18-30",
        "Called from file \"src/lib/network_pool/network_pool_base.ml\", line 101, characters 15-67",
        "Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 155, characters 28-37",
        "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
        "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
        "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
      ]
    },
    "host": "88.202.186.21",
    "peer_id": "12D3KooWRGp4UUgo2LKSEF8GpDNyd2iboyX4ZrVZqqVqzwKVLsbU",
    "pid": 1807,
    "port": 8302
  }
}
```

This is a duplicate of #6949. Closing.

**Closed by mrmr1993** 2021-01-08 13:00 UTC
