### ISSUE TITLE
Blockchain_snark failure

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#14574] opened 2023-11-17 19:29 UTC
I find this blockchain snark failure while debugging #14523:
```
{
  "error": {
    "commit_id": "4061884b18137c1182c7fcfa80f52804008a2509",
    "exn_name": "Base__Exn.Sexp",
    "exn": [
      "monitor.ml.Error",
      [
        "Failure",
        "Constraint unsatisfied (unreduced):\nChecked.Assert.equal\nFile \"src/lib/blockchain_snark/blockchain_snark_state.ml\", line 237, characters 17-24\nstep: File \"src/lib/blockchain_snark/blockchain_snark_state.ml\", line 141, characters 0-9581\nrule_main\nstep_main\n\nConstraint:\n((basic(Equal(Var 30504)(Var 67)))(annotation(Checked.Assert.equal)))\nData:\nEqual 27573854971309006524707318668807907506392736706272209516676860244191550005741 7457198107900010210387056950262616376618306631506029673032554931013040883939"
      ],
      [
        "Raised at Base__Exn.protectx in file \"src/exn.ml\", line 71, characters 4-114",
        "Called from Async_kernel__Monitor.Exported_for_scheduler.schedule'.upon_work_fill_i in file \"src/monitor.ml\", line 295, characters 42-51",
        "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5",
        "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 169, characters 6-47",
        "Caught by monitor at file \"src/lib/prover/prover.ml\", line 116, characters 52-52"
      ]
    ]
  }
}
```

**Comment by mrmr1993** [comment] 2024-08-31 12:22
Investigation showed that this was caused by the same as https://github.com/MinaProtocol/mina/issues/14613. Closing in favour of that issue.

**Closed by mrmr1993** 2024-08-31 12:22 UTC
