### ISSUE TITLE
Allow user commands from snapp accounts?

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#10191] opened 2022-02-09 00:40 UTC
There's a check that prevents executing user commands on snapp accounts:

https://github.com/MinaProtocol/mina/blob/feature/snapps-protocol/src/lib/mina_base/transaction_logic.ml#L681

Is this check justified?

**Comment by deepthiskumar** [comment] 2022-03-16 18:39
duplicate of 10402

**Closed by deepthiskumar** 2022-03-16 18:40 UTC
Labels: Proj - snapps protocol work, snapps-before-testnet
