### ISSUE TITLE
iOS Safari support for snarkyJS

### ISSUE THREAD

**Issue by halsaphi** [MinaProtocol/mina#13293] opened 2023-05-29 02:51 UTC
Currently iOS Safari is not supported by snarkyJS. In order to encourage as wide adoption as possible add snarkyJS support to iOS Safari

**Comment by shimkiv** [comment] 2023-05-29 05:52
https://github.com/o1-labs/snarkyjs/issues/823#issuecomment-1565757386

**Comment by mrmr1993** [comment] 2024-08-31 14:08
Duplicate of https://github.com/o1-labs/o1js/issues/823, which is resolved.

**Closed by mrmr1993** 2024-08-31 14:08 UTC
