### ISSUE TITLE
Trying to restart

### ISSUE THREAD

**Issue by jflowers1974** [MinaProtocol/mina#6963] opened 2020-12-07 01:55 UTC
Been having issues re-starting my node.

[coda_crash_report_2020-12-07_01-49-15.240811.tar.gz](https://github.com/MinaProtocol/mina/files/5650010/coda_crash_report_2020-12-07_01-49-15.240811.tar.gz)

**Comment by garethtdavies** [comment] 2020-12-07 02:12
`Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"c275e4c9-aaed-3712-bb00-336d89c4f383\"`

Duplicate of https://github.com/MinaProtocol/mina/issues/6949 and https://github.com/MinaProtocol/mina/issues/6935 - the latter indicating it resolves itself after a couple of crashes?

**Comment by mrmr1993** [comment] 2021-01-08 13:03
Closing as a duplicate of #6949.

**Closed by mrmr1993** 2021-01-08 13:03 UTC
