### ISSUE TITLE
Mina-QA: archive node can't sync properly

### ISSUE THREAD

**Issue by c29r3** [MinaProtocol/mina#6537] opened 2020-10-28 20:51 UTC
## Description  
Node can't sync for 4 hours. During synchronization, node crashed several times

<details>
  <summary>Coda client status </summary>

```
Coda daemon status
-----------------------------------

Global number of accounts:       77
Block height:                    293
Max observed block length:       589
Local uptime:                    54m15s
Ledger Merkle root:              jwWvAMnXXtuwJSPM9LLdEhHNzYsS2zhJHZ3yESJrwVk7561M6BV
Protocol state hash:             3NKZ4aEhB88vLUgjR7vt7d8ZjZQ2ed7H8KCMuqM1H5pnndTxDnLY
Chain id:                        a5f4406aa626266738860c5a6a5ffdff32c6eb55c61b0640a543916ba0808ba5
Git SHA-1:                       [DIRTY]6dc573d304cf05e3d0107b61901b3b816ab06b15
Configuration directory:         /root/.coda-config
Peers:                           16 (141.154.11.189:56661 35.237.193.100:10511 34.75.79.94:10001 34.75.8.249:10503 34.73.107.111:10506 36.189.234.171:8302 34.75.40.155:10401 34.75.81.35:10909 35.237.156.30:10501 35.196.239.97:10508 35.190.167.193:10509 144.91.83.29:55742 35.190.167.193:10001 35.231.237.219:10504 34.75.59.183:10502 34.73.89.213:10510)
User_commands sent:              0
SNARK worker:                    None
SNARK work fee:                  25000000
Sync status:                     Synced
Block producers running:         1 (B62qp6PvbR69ip9a1ZRy47ryGqVSWVrWJ19fhPVDJBZ6x2S8AKyL5Lc)
Best tip consensus time:         epoch=0, slot=1100
Next block will be produced in:  in 1.821h
Consensus time now:              epoch=0, slot=2179
Consensus mechanism:             proof_of_stake
Consensus configuration:         
	Delta:                     0
	k:                         290
	Slots per epoch:           7140
	Slot duration:             2m
	Epoch duration:            9d22h
	Genesis state timestamp:   2020-10-25 19:36:43.000000Z
	Acceptable network delay:  2m

Addresses and ports:             
	External IP:    95.165.167.193
	Bind IP:        0.0.0.0
	Libp2p PeerID:  12D3KooWFJHxaxu5fWLkNYbuuAC5w4eFAQE6HVRo4m2jG7ZWDq12
	Libp2p port:    8302
	Client port:    8301
```

</details>  

## Environment  
```
Git SHA-1: [DIRTY]6dc573d304cf05e3d0107b61901b3b816ab06b15
Host OS: Ubuntu 20.04  
Using containerization: docker  
CPU: i5 6400  
RAM: 16 GB  
```

## Steps to reproduce  
1. Forwarded ports on my router: 8302, 8303\TCP  
![image](https://user-images.githubusercontent.com/52304443/97493384-ed6ace80-1975-11eb-87df-f310a38e4758.png)  
2. Create docker from ubuntu:18.04 image  
3. Standard installation from the repository, according to the instructions from `#qa-task-force` pin message  
4. Commit changes to new docker image  
5. Run new docker instance  
```
docker run -d \
  --restart always \
  --entrypoint /root/daemon_start.sh \
  --volume /home/mina/crypto/mina/keys:/root/keys \
  --volume /home/mina/crypto/mina/daemon_start.sh:/root/daemon_start.sh \
  --volume /home/mina/crypto/mina/coda-config:/root/.coda-config \
  --env KEYPATH=/root/keys/my-wallet \
  --env CODA_PRIVKEY_PASS=12345 \
  --name mina-qa-test \
  -p 8302:8302 \
  -p 8303:8303 \
  --log-opt max-size=100m \
  --log-opt max-file=3 \
  c29r3/mina-qa-test
```  

<details>
  <summary>daemon_start.sh</summary>
  
  The values ​​PEER1 and PEER2 are omitted, as this is non-public information
  
  ```bash
#!/bin/bash
coda daemon -peer $PEER1 \
  -peer $PEER2 \
  -config-file /root/daemon.json \
  -generate-genesis-proof true \
  -block-producer-key "${KEYPATH}" \
  -log-level Info
  ```
  
</details>

## LOGS  
https://drive.google.com/drive/folders/1dqXZDTkhRW_3dtFjm6wUgM5xtFRDIbKt?usp=sharing

**Comment by c29r3** [comment] 2020-10-28 23:46
UPD:  
As a result, the node was synchronized
```
Coda daemon status
-----------------------------------

Global number of accounts:       81
Block height:                    603
Max observed block length:       602
Local uptime:                    4h24m57s
Ledger Merkle root:              jxrZL2tDGqDVvMQkA7bmmju6LpEEE91tNmDGccLeGhK26MsUt3Z
Protocol state hash:             3NLU2WfkBMGqxhf7fvUpvxuUXiSsMbAsCUUYBCJdtMnoaUTt6RPp
Chain id:                        a5f4406aa626266738860c5a6a5ffdff32c6eb55c61b0640a543916ba0808ba5
Git SHA-1:                       [DIRTY]6dc573d304cf05e3d0107b61901b3b816ab06b15
Configuration directory:         /root/.coda-config
Peers:                           17 (35.196.239.97:10508 35.237.193.100:10511 34.75.59.183:10502 104.196.108.77:10503 34.75.79.94:10001 141.154.11.189:56661 34.73.107.111:10506 35.185.50.48:59956 36.189.234.171:8302 34.73.89.213:10510 35.237.120.198:48646 34.75.40.155:10401 35.237.156.30:10501 35.190.167.193:10509 144.91.83.29:55742 35.190.167.193:10001 34.75.81.35:10909)
User_commands sent:              0
SNARK worker:                    None
SNARK work fee:                  25000000
Sync status:                     Synced
Block producers running:         1 (B62qp6PvbR69ip9a1ZRy47ryGqVSWVrWJ19fhPVDJBZ6x2S8AKyL5Lc)
Best tip consensus time:         epoch=0, slot=2283
Next block will be produced in:  in 20.757m
Consensus time now:              epoch=0, slot=2284
Consensus mechanism:             proof_of_stake
Consensus configuration:         
	Delta:                     0
	k:                         290
	Slots per epoch:           7140
	Slot duration:             2m
	Epoch duration:            9d22h
	Genesis state timestamp:   2020-10-25 19:36:43.000000Z
	Acceptable network delay:  2m

Addresses and ports:             
	External IP:    95.165.167.193
	Bind IP:        0.0.0.0
	Libp2p PeerID:  12D3KooWFJHxaxu5fWLkNYbuuAC5w4eFAQE6HVRo4m2jG7ZWDq12
	Libp2p port:    8302
	Client port:    8301

```

**Comment by nholland94** [comment] 2020-11-11 19:43
It appears as though your node was crashing during the bootstrap phase due to the following error:
```
(monitor.ml.Error
  ("Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference("a96310ae-8398-3f5e-b988-e52deb3a198a")")
  ("Raised at file "src/lib/merkle_mask/masking_merkle_tree.ml", line 101, characters 10-50"
    "Called from file "src/lib/merkle_mask/masking_merkle_tree.ml", line 245, characters 6-26"
    "Called from file "src/lib/staged_ledger/staged_ledger.ml", line 499, characters 37-71"
    "Called from file "src/lib/staged_ledger/staged_ledger.ml", line 510, characters 52-67"
    "Called from file "src/lib/staged_ledger/staged_ledger.ml", line 509, characters 6-110"
    "Called from file "src/lib/staged_ledger/staged_ledger.ml", line 556, characters 20-213"
    "Called from file "list.ml", line 117, characters 24-34"
    "Called from file "src/deferred1.ml", line 17, characters 40-45"
    "Called from file "src/job_queue.ml" (inlined), line 131, characters 2-5"
    "Called from file "src/job_queue.ml", line 171, characters 6-47"
    "Caught by monitor coda"))
```

We have seen this crash before. Here are some prior reasons why we have seen this:

https://github.com/MinaProtocol/mina/issues/4480#issuecomment-593602222
https://github.com/MinaProtocol/mina/issues/4041#issuecomment-565174413

If the latter of those two explanations is still valid, it's possible that the fix for this could be to finally implement RFC 28 (introduced here #4100). #4157 captures the work necessary for this. More investigation is required before I can confirm that this is the root cause in this case, though. We will need to recreate this condition, as it appears the necessary information required to debug this is not available in the logs that were uploaded with the crash (they look as if they were generated from a subsequent run of the daemon, and not from the same run the crash happened in). The short log in the crash is not useful due to too much libp2p output during graceful shutdown.

**Comment by raghulraj** [comment] 2020-12-20 23:44
Seeing the issue on testnet 4.1, please find below tgz for crash report.

[coda_crash_report_2020-12-20_23-29-03.925296.tar.gz](https://github.com/MinaProtocol/mina/files/5721697/coda_crash_report_2020-12-20_23-29-03.925296.tar.gz)

**Comment by dewrin** [comment] 2020-12-20 23:48
2020-12-20 23:44:01 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "sexp": [
    "Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"82f2fd52-da10-3147-62ad-e0d8d961accb\", \"File \\\"src/lib/transition_router/transition_router.ml\\\", line 508, characters 61-68\")"  ],
  "backtrace": [
    "Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57",
    "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 121, characters 6-26",
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1165, characters 29-65",
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1178, characters 18-30",
    "Called from file \"src/lib/network_pool/network_pool_base.ml\", line 101, characters 15-67",
    "Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 155, characters 28-37",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-12-20 23:44:01 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"


  ☠  Coda Daemon crashed.

**Comment by mrmr1993** [comment] 2021-01-08 13:06
Closing as a duplicate of #6949.

**Closed by mrmr1993** 2021-01-08 13:06 UTC
Labels: bug, impacts users, needs research
