### ISSUE TITLE
Same BP key on 2 node got different slot

### ISSUE THREAD

**Issue by scraido** [MinaProtocol/mina#14515] opened 2023-11-05 12:09 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

After move the --max-connections 200 on .mina-env and Mina.service, i got 2 different slot for the same BP key

### Steps to Reproduce

1. Maybe remove the --max.. string and then what i do is
2. rm -rf mina.config
3. Do fresh installation
...

### Expected Result

Maybe i should get same slot on the two machine

### Actual Result

I got 2 different slot with the same BP keys, please take a look at the SS
![Screenshot_20231105-103900](https://github.com/MinaProtocol/mina/assets/44559893/7d09952c-7f7d-4665-ac58-f26f9bdc0831)

Another one.
![Screenshot_20231105-103950](https://github.com/MinaProtocol/mina/assets/44559893/7b9d15dd-4383-4978-bb84-467137812370)

### How frequently do you see this issue?

Rarely

### What is the impact of this issue on your ability to run a node?

Low

### Status

```shell
Not sure how to copy pasting it using android 🙏
```

### Additional information

I did rm -rf coz when rem --max.. string also in .mina-env, it causing me experience fatal err., but the err. was vanish when i rm -rf the mina.config <dir>

But this also gave me uptime = 0 now, when checked it thru this sintax$; since="24h ago" && echo && echo "Uptime service - sent : $(journalctl -u mina -S "$since" | grep 'Sent block with state' | wc -l), failed: $(journalctl -u mina -S "$since" | grep 'After 8 attempts, failed' | wc -l)"

I'll send the logs a.s.a.p. to logs@o1labs.org 🙏

**Comment by ghost-not-in-the-shell** [comment] 2023-11-28 18:42
This could be related to this issue: #14613. The root cause of this is that block producer does vrf evaluation before catchup finishes and the thus chose the wrong epoch ledger (this didn't happen every time, it could only happens when the node is bootstrap to a state where epoch snapshot is not finalized and picure 1 in this issue seems to be a good candidate of that.

**Comment by mrmr1993** [comment] 2024-08-31 12:25
Closing in favour of https://github.com/MinaProtocol/mina/issues/14613.

**Closed by mrmr1993** 2024-08-31 12:25 UTC
Labels: bug, triage, Testworld-2-0-protocol-performance-testing
