### ISSUE TITLE
Coda Daemon crashed with RocksDb error during startup

### ISSUE THREAD

**Issue by roadtobitcoin** [MinaProtocol/mina#7286] opened 2020-12-31 07:04 UTC
I am just running the command CODA_PRIVKEY_PASS="**my email password" coda daemon -peer-list-file ~/peers.t
xt -block-producer-key ~/keys/my-wallet -generate-genesis-proof true -file-log-level Info**

and got below error of crashed. 

```
2020-12-31 06:48:39 UTC [Info] Coda daemon is booting up; built with commit "[DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af" on branch "HEAD"
2020-12-31 06:48:39 UTC [Info] Removing lockfile for terminated process
2020-12-31 06:48:39 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2020-12-31 06:48:39 UTC [Info] Booting may take several seconds, please wait
2020-12-31 06:48:39 UTC [Info] Reading configuration files $config_files
        config_files: [
  "/var/lib/coda/config_b7eff8e5.json",
  "/home/ntnmodgil10/.coda-config/daemon.json"
]
2020-12-31 06:48:39 UTC [Warn] Could not read configuration from "/home/ntnmodgil10/.coda-config/daemon.json": $error
        error: {
  "exn_name": "Async_kernel__Monitor.Error_",
  "exn":
    "(monitor.ml.Error\n  (Unix.Unix_error \"No such file or directory\" open\n    \"((filename /home/ntnmodgil10/.coda-config/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))\")\n  (\"Raised at file \\\"src/result.ml\\\", line 158, characters 17-26\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor try_with_or_error\"))"
}
2020-12-31 06:48:39 UTC [Info] Initializing with runtime configuration. Ledger name: "testworld"
2020-12-31 06:48:39 UTC [Info] Using the compiled constraint constants
2020-12-31 06:48:40 UTC [Info] Found genesis proof file at $path
        path: "/home/ntnmodgil10/.coda-config/genesis/genesis_proof_2eba002d6bc68b79ef1986f747c235f74393f60d4a77cd1383f125cfb5f5bf6d"
2020-12-31 06:48:40 UTC [Info] Loaded ledger from $ledger_file and genesis proof from $proof_file
        ledger_file: "/home/ntnmodgil10/.coda-config/genesis/genesis_ledger_accounts_a0a52362cff41dde1644de9ce44aabd673c5e1e6eed9caaff7ea906b5fe3e988_74bedf9d2d01e70156df8f82da3ba62449a392d67b3de4de3523aca975e0d467.tar.gz"
        proof_file: "/home/ntnmodgil10/.coda-config/genesis/genesis_proof_2eba002d6bc68b79ef1986f747c235f74393f60d4a77cd1383f125cfb5f5bf6d"
2020-12-31 06:48:41 UTC [Fatal] Unhandled top-level exception: $exn

Generating crash report
        exn: {
  "sexp": [
    "Failure",
    "IO error: While lock file: /home/ntnmodgil10/.coda-config/trust/LOCK: Resource temporarily unavailable"
  ],
  "backtrace": [
    "Raised at file \"stdlib.ml\", line 33, characters 17-33",
    "Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63",
    "Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33",
    "Called from file \"src/app/cli/src/coda.ml\", line 849, characters 25-54",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}


  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /home/ntnmodgil10/.coda-config/coda_crash_report_2020-12-31_06-48-41.147621.tar.gz
```

**Comment by mrmr1993** [comment] 2020-12-31 10:25
This is a duplicate of #7275. Closing in favour of that issue, which has an attached log file.

**Closed by mrmr1993** 2020-12-31 10:25 UTC
