### ISSUE TITLE
Document the Nix code and make it more maintainable

### ISSUE THREAD

**Issue by balsoft** [MinaProtocol/mina#12090] opened 2022-11-01 08:07 UTC

**Comment by kantp** [comment] 2022-11-04 09:38
@balsoft Is this already ini progress? I thought you mentioned you'd been working on this?

**Comment by kantp** [comment] 2022-11-04 09:39
Also, this might be a duplicate of #10003?

**Comment by michal0mina** [comment] 2022-12-07 09:29
Implemented and merged here: https://github.com/MinaProtocol/mina/pull/12287

**Comment by robinbb** [comment] 2023-01-02 20:49
@michal0mina This issue is in the Done column, but still not closed. What is the correct status, in your opinion? Can we close this issue?

**Comment by michal0mina** [comment] 2023-01-05 13:17
@robinbb yes, we can close.

**Closed by michal0mina** 2023-01-05 13:17 UTC
Labels: MinaFoundation
