### ISSUE TITLE
Require that fees be positive in construction.

### ISSUE THREAD

**Issue by Sventimir** [MinaProtocol/mina#12452] opened 2023-01-05 12:52 UTC
Our Construction API implementation silently assumes that `fee_payment` operations will always have negative amounts of Mina assigned to them. This is not enforced by the specification and neither could I find any documentation that would explain it. Yet, if a user specifies a positive `fee_payment` amount, the system will return a transaction with an astronomically high value (because the value is then negated modulo `2^64`). To avoid confusion and potential errors, we sholuld throw an error if a user provdes a positive `fee_payment` amount.

**Comment by ejMina226** [comment] 2023-01-10 10:00
Closing as duplicate of #12469

**Closed by ejMina226** 2023-01-10 10:00 UTC
Labels: rosetta, MinaFoundation
