### ISSUE TITLE
seed node 4 on finalfinal2 crashed constantly due to wnohang

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#8126] opened 2021-03-05 18:07 UTC
from 3/4/2021 - 3/5/2021, seed node 4 crashed almost every 15 mins. Most of the crashes is due to wnohang.

**Comment by nholland94** [comment] 2021-03-09 22:18
Closing in favor of #8166, which captures what we believe is the root cause of this bug.

**Closed** 2021-03-09 22:19 UTC
