### ISSUE TITLE
Document anatomy of a parties transaction

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#10031] opened 2022-01-17 22:53 UTC
Skeleton is here:  https://www.notion.so/minaprotocol/Parties-Transaction-Anatomy-917a5f2eabb2468e97387bbcac7214d2

**Comment by deepthiskumar** [comment] 2022-03-04 02:07
duplicate of #9959

**Closed by deepthiskumar** 2022-03-04 02:07 UTC
Labels: Size: S ~ 0.5 wks, accelerate
