### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by dewrin** [MinaProtocol/mina#6864] opened 2020-11-26 13:34 UTC
{"OS_type":"Unix","Release":"5.4.0-1031-azure","Machine":"x86_64","Sys_name":"Linux","Exception":{"sexp":["Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"c08f9f16-ceea-3239-600d-6ee7ef81425e\")"],"backtrace":["Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 101, characters 10-50","Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 513, characters 6-26","Called from file \"src/lib/network_pool/transaction_pool.ml\", line 877, characters 24-75","Called from file \"src/lib/network_pool/transaction_pool.ml\", line 880, characters 26-68","Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1117, characters 18-30","Called from file \"src/lib/network_pool/network_pool_base.ml\", line 93, characters 15-67","Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 152, characters 28-37","Called from file \"src/deferred0.ml\", line 56, characters 64-69","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"Command":"Command: (coda daemon -peer-list /home/maragung/peers.txt -run-snark-worker\n B62qpWMS4Z9Q3AP85EnMnad62QfhHiFYLYb4yRGzTJwT2GK1FusXbZ5 -snark-worker-fee 1)","Coda_branch":"HEAD","Coda_commit":"[DIRTY]7f0440c609bfd1e2bc4130f06d09f72763c25b67"}

**Comment by mrmr1993** [comment] 2021-01-08 13:07
Closing as a duplicate of #6949.

**Closed by mrmr1993** 2021-01-08 13:07 UTC
