### ISSUE TITLE
problem with Process killed because out of memory and validation callback timed out before we could respond

### ISSUE THREAD

**Issue by taoros** [MinaProtocol/mina#7912] opened 2021-02-15 20:43 UTC
Hello, 

in the past era and in Encore, the node itself begins to lag behind the high block
helps to restart the node.
I understand that I will overload and everything will be ok but this is not normal

now block 6603
I seem to understand what happened, at first  Process killed because out of memory
then validation callback timed out before we could respond.... 
but the status of the node has not changed uptime node more than 4 days
I have a server 16cpu and 32gb memory

![image](https://user-images.githubusercontent.com/35835975/107990499-402bcd00-6fdd-11eb-938b-0fdffa8ea957.png)

![image](https://user-images.githubusercontent.com/35835975/107990625-7cf7c400-6fdd-11eb-9579-8c6cb6bf9b6b.png)

[mina.zip](https://github.com/MinaProtocol/mina/files/5984005/mina.zip)

pay attention to the time  - 2021-02-12 14:52:13.849152
thanks.

**Comment by mrmr1993** [comment] 2021-03-19 02:04
This sounds like issue #7555: the verifier should have attempted to restart after being killed, but because of that issue it doesn't restart and the node gets stuck. We're currently testing a fix for this issue.

Closing as duplicate of #7555.

**Closed by mrmr1993** 2021-03-19 02:04 UTC
