### ISSUE TITLE
Pri keys pass

### ISSUE THREAD

**Issue by Nightguy1688** [MinaProtocol/mina#9242] opened 2021-07-21 09:24 UTC
Version gcr.io/o1labs-192920/mina-daemon:1.2.0beta2-23842ac-mainnet pri key pass will get corrupted after a few days?.

**Comment by rashidovich** [comment] 2021-07-22 08:21
I was bale to replicate same issue. At first, when I've just installed 1.2.0beta2 - I could unlock my account, but after some time (possibly few client container restarts), I'm no longer able to do it.

![image](https://user-images.githubusercontent.com/5165742/126609558-4675e585-a4e2-436f-8db1-5c89671be870.png)

**Comment by vaniawp** [comment] 2021-07-28 09:19
Same error for me too

`$ mina accounts unlock --public-key XXXXXXXXXXX`
`Using password from environment variable CODA_PRIVKEY_PASS`
`Using password from environment variable CODA_PRIVKEY_PASS`
`Using password from environment variable CODA_PRIVKEY_PASS`
`❌ Error: Wrong password provided (in ["unlockAccount"])`

Was well before system reboot and daemon start. Daemon launched with same key data without any problems, but unlock command gives this error. 
Non docker Ubuntu 20.04

**Comment by lampardlamps** [comment] 2021-09-13 19:37
have had the issue (`❌ Error: Wrong password provided (in ["unlockAccount"])`) from early beta releases and it persists in beta5 too. My configs are:
OS: ubuntu 18.04
hardware: 16c 32gb vps on AWS
mina version: beta 5 and earlier beta releases
misc: tried `cat cat ~/.mina-config/wallets/store/B62xx.pub` and `cat cat ~/.mina-config/wallets/store/B62xx`, can read the files okay.

**Comment by lampardlamps** [comment] 2021-09-13 19:39
> Version gcr.io/o1labs-192920/mina-daemon:1.2.0beta2-23842ac-mainnet pri key pass will get corrupted after a few days?.

hi @Nightguy1688 , would it be possible to change the issue title to something like `1.2.0 beta: corrupted keys after a few days` please? Thanks.

**Comment by psteckler** [comment] 2021-09-14 16:21
I'm trying to understand what's going wrong here. I think it's unlikely that the key files would change over time.

This issue arises when running the daemon in a container? Is the password in `CODA_PRIVKEY_PASS` known to be correct, and not change across restarts?

**Comment by jrwashburn** [comment] 2021-09-14 16:30
> This issue arises when running the daemon in a container? 

@lampardlamps reports the same issue not running in a container - see above.

**Comment by lampardlamps** [comment] 2021-09-14 16:39
> At some point, `CODA_PRIVKEY_PASS` was replaced by `MINA_PRIVKEY_PASS`. Have you tried using that?

Yes, also tried directly inputing the pwd, no luck. just says `❌ Error: Wrong password provided (in ["unlockAccount"])`

**Comment by psteckler** [comment] 2021-09-14 16:57
I just had a look at the sources in the `release/1.2.0` branch.

It looks like there are several things that can go wrong when unlocking a key, and they all get merged into `Bad_password`, making this hard to track down.

@jrwashburn When this happens, can you run `sha1sum` on the imported private key file, and compare that against `sha1sum` on the original private key file? That would reveal if the file has changed in some way.

**Comment by jrwashburn** [comment] 2021-09-14 16:58
I cannot reproduce. @lampardlamps or @Nightguy1688 should be able to though.

**Comment by psteckler** [comment] 2021-09-14 17:06
I'll also ask, @rashidovich Are you able to run `sha1sum` on the original and imported private key file, when this error occurs?

**Comment by lampardlamps** [comment] 2021-09-14 17:07
Yeah I tried and paid more attention to details this time. with `cat <pub key>` the results return the same, but with `cat <priv key>`, the `nouce` and `ciphertext` fields are different from the original key, all the other fields are the same. The `sha1sum` commands return different results of course.

**Comment by psteckler** [comment] 2021-09-14 17:09
> the nouce and ciphertext fields are different from the original key

That is weird, indeed. I'll investigate.

**Comment by psteckler** [comment] 2021-09-14 17:16
@lampardlamps Does the modified private key file correspond to any other private key file you have on your system?

**Comment by lampardlamps** [comment] 2021-09-14 17:20
no, none of it. Thanks for looking into it btw.

**Comment by psteckler** [comment] 2021-09-14 21:46
@jrwashburn Are you using the same key for block production and the uptime service on the command line?

**Comment by psteckler** [comment] 2021-09-14 23:09
@lampardlamps is it possible that you used a different password when importing the key than you used when creating the key?  That would explain why the files are different.

**Comment by lampardlamps** [comment] 2021-09-14 23:14
I don't think so - I've always copy pasted the same pwd.

**Comment by lampardlamps** [comment] 2021-09-15 10:14
@psteckler I've deleted the corrupted key in `.mina-config` and restarted the daemon, and imported and unlocked the keys again. This works, but when `cat` the keys in `.mina-config` still are different from the original. I checked the pwd, in `.mina-env` I had `CODA_PRIVKEY_PASS="pwd"` whereas I unlocked with `CODA_PRIVKEY_PASS=pwd` with out `"` otherwise the strings are the same, could that be the issue?

**Comment by psteckler** [comment] 2021-09-15 23:00
> I checked the pwd, in `.mina-env` I had `CODA_PRIVKEY_PASS="pwd"` whereas I unlocked with `CODA_PRIVKEY_PASS=pwd` with out `"` or directly input `pwd` when promted, otherwise the strings are the same, could that be the issue please?

Not sure, really. That file is used by `systemd` when running a service, and I'm not really familiar with how double-quoting environment variables works there.

**Comment by lampardlamps** [comment] 2021-09-16 08:20
Thanks. Not sure you've seen my edits above, but I tried CODA_PRIVKEY_PASS="pwd" in command line, and `cat` returns the third different privkey reading from the previous two...

**Comment by psteckler** [comment] 2021-09-16 15:51
Created #9499, which allows providing the uptime submitter keyfile directly.

That won't help with instances of this issue not related to the uptime service, of course.

**Comment by jrwashburn** [comment] 2021-09-21 14:02
> @jrwashburn Are you using the same key for block production and the uptime service on the command line?

Yes

**Comment by wjdfx** [comment] 2021-11-10 04:24
> unlock account problems exist on the latest version " gcr.io/o1labs-192920/mina-daemon:1.2.0beta8-5b3

Yes, looks like version `Commit fe51f1ef5cfbcb4d5f559af39080963cf28ff1af on branch master` still have same problem

**Comment by Nightguy1688** [comment] 2021-11-10 09:34
> 
> 
> > unlock account problems exist on the latest version " gcr.io/o1labs-192920/mina-daemon:1.2.0beta8-5b3
> 
> Yes, looks like version `Commit fe51f1ef5cfbcb4d5f559af39080963cf28ff1af on branch master` still have same problem

Yes but can be over come by importing your keys to daemon first.

**Comment by jkrauska** [comment] 2022-01-18 19:46
@psteckler any news on this bug or a timeline/prioritization?   Gets me every time.

**Comment by jkrauska** [comment] 2022-01-18 19:49
Also occurs in Commit feee67cc2836bf12e792510a2440f28a0275740e on branch master

**Comment by xubincc** [comment] 2022-03-24 02:03
unlock account problems exist on the latest version
Commit 9b0369c27bb85c8ab2f8725c6e977eb27b53b826 on branch master
❌ Error: Error reading the secret key file: The password was incorrect, or the key is corrupted (in ["unlockAccount"])

**Comment by psteckler** [comment] 2022-03-29 05:49
> unlock account problems exist on the latest version

@xubincc When was your key imported?

With the latest versions, newly-imported keys should not have this problem. If the key was imported before the fix, you'll still see this behavior (because the key was saved with an incorrect password).

The fix is to delete the key from the wallet, and re-import it.

**Comment by humantraffic** [comment] 2022-05-25 08:12
> > unlock account problems exist on the latest version
> 
> @xubincc When was your key imported?
> 
> With the latest versions, newly-imported keys should not have this problem. If the key was imported before the fix, you'll still see this behavior (because the key was saved with an incorrect password).
> 
> The fix is to delete the key from the wallet, and re-import it.

i have same problen on mina-daemon:1.3.1-3e3abec-focal-mainnet daemon
`FATAL ERROR

  ☠  Mina Daemon encountered a configuration error loading block producer keypair.

The password was incorrect, or the key is corrupted
Mina process exited with status code 1`

**Comment by Nightguy1688** [comment] 2022-05-25 17:13
Hello,

I don't have such errors anymore even with the latest version providing if running docker with " --mount "type=bind,source=`pwd`/.mina-config,dst=/root/.mina-config" \ " .If you guys have further problems please ask Beacon chain as he guided me from the begining.



    On Wednesday, 25 May 2022, 09:08:44 BST, humantraffic ***@***.***> wrote:  
 
 




unlock account problems exist on the latest version


@xubincc When was your key imported?

With the latest versions, newly-imported keys should not have this problem. If the key was imported before the fix, you'll still see this behavior (because the key was saved with an incorrect password).

The fix is to delete the key from the wallet, and re-import it.


i have same problen on mina-daemon:1.3.1-3e3abec-focal-mainnet daemon

  ☠  Mina Daemon encountered a configuration error loading block producer keypair.

The password was incorrect, or the key is corrupted
Mina process exited with status code 1```

**Comment by psteckler** [comment] 2022-05-25 17:22
> i have same problen on mina-daemon:1.3.1-3e3abec-focal-mainnet daemon 

@humantraffic Can you tell me the exact steps you used, to import the key, then to run the daemon? That will help me track down the issue.

**Comment by Nightguy1688** [comment] 2022-05-25 20:45
If you are running docker then add this bind flag  " --mount "type=bind,source=`pwd`/.mina-config,dst=/root/.mina-config" \ " then import as normal .It works for all daemon versions upgrade for me so far.
Or ask Beacon chain since he guided me this method from start.

**Comment by cryptoved** [comment] 2022-05-26 11:26
I can make transactions on previous Mina version but on the last one after this commands:

sudo docker exec -it mina mina accounts import -privkey-path $Home/keys/my-wallet 
sudo docker exec mina mina accounts list
sudo docker exec -it mina mina accounts unlock -public-key $MINA_PUBLIC_KEY

I have error:
❌ Error: Error reading the secret key file: The password was incorrect, or the key is corrupted (in ["unlockAccount"])
What should I do to resolve it?

I run node with such commands:
sudo docker run --name mina -d \
-p 8302:8302 \
--network mina-network \
--restart=always \
--mount "type=bind,source=`pwd`/keys,dst=/keys,readonly" \
--mount "type=bind,source=`pwd`/.mina-config,dst=/root/.mina-config" \
--env MINA_PRIVKEY_PASS='mypass' \
--env UPTIME_PRIVKEY_PASS='mypass' \
minaprotocol/mina-daemon:1.3.1-3e3abec-bionic-mainnet daemon \
--block-producer-key /keys/my-wallet \
--open-limited-graphql-port \
--limited-graphql-port 3095 \
--insecure-rest-server \
--file-log-level Debug \
--log-level Info \
--peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt \
--uptime-submitter-key $KEYPATH \
--uptime-url https://uptime-backend.minaprotocol.com/v1/submit

**Comment by humantraffic** [comment] 2022-05-26 11:39
did you put the keys in the folder?

**Comment by cryptoved** [comment] 2022-05-26 11:43
> did you put the keys in the folder?

yes
Now I try to do using this solution: https://github.com/MinaProtocol/mina/issues/9720

**Comment by humantraffic** [comment] 2022-05-26 11:45
> > did you put the keys in the folder?
> 
> yes Now I try to do using this solution: #9720

del container and delete folder .mina-config and run

**Comment by psteckler** [comment] 2022-09-20 20:44
Closing, can be re-opened if the problem persists.

**Closed by psteckler** 2022-09-20 20:44 UTC
Labels: priority-medium, triage

**Comment by mrdomino** [comment] 2024-01-19 02:59
So, long story short — if I find that I have a `my-wallet` privkey file lying around in a backup somewhere, and it does not unlock with the deterministic password that I generated for it, then it is most likely because it fell prey to this issue? And there's no way to recover the wallet?

(It's not a major amount of money, just checking.)

**Comment by lampardlamps** [comment] 2024-01-19 14:57
You simply need to restart the node for it to unlock.

Jōshin ***@***.***> 于 2024年1月19日周五 上午2:59写道：

**Comment by lampardlamps** [comment] 2024-01-19 15:00
Apologies - you need to use the two commands as outlined by others in the
thread for it to unlock. Also this has been resolved by newer versions
already.


sudo rm ~/.mina-config/wallets/store/PUBLICKEYADDRESS.pub #where
PUBLICKEYADDRESS is your address
sudo docker restart mina

lamps ***@***.***> 于 2024年1月19日周五 下午2:57写道：
