### ISSUE TITLE
Alert errors in replayer cronjob

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#13506] opened 2023-06-29 23:44 UTC

**Comment by deepthiskumar** [comment] 2023-06-29 23:45
Cron job added as part https://github.com/MinaProtocol/mina/issues/12993. Any mismatch is data(ledger hash, balance, nonce etc) should be alerted

**Comment by psteckler** [comment] 2023-06-30 17:22
Duplicate of #13472.

**Closed by psteckler** 2023-06-30 17:22 UTC
