### ISSUE TITLE
Producing new block and than Coda process exited with status code 137

### ISSUE THREAD

**Issue by EmreNOP** [MinaProtocol/mina#7306] opened 2021-01-03 13:29 UTC
**2021-01-03 04:11:30** UTC [Info] Producing new block with parent $breadcrumb
	breadcrumb: {
  "validated_transition": {
    "data": {
      "protocol_state": {
        "previous_state_hash":
          "3NLj877P2QHSSah2pzbCSsGgyU5YkW5BuhCS4Nh7YRCXV56SVKrw",
        "body": {
          "genesis_state_hash":
            "3NLxYrjb7zmHdoFgBrubCN8ijM8v7eT8kvLiPLc9DHt3M8XrDDEG",
          "blockchain_state": {
            "staged_ledger_hash": {
              "non_snark": {
                "ledger_hash":
                  "jwQgaLpcTnMxzRpgNuSgNnJyLti5HCJkfpQTqacmnWKCuy75aMN",
                "aux_hash":
                  "VgnnBogneoaqXALhRLsVb5XwfjhfkBnC4hp3gx1FauWxccZhwY",
                "pending_coinbase_aux":
                  "XUEeguj2J8Bj3knNEQz2GSFPTsdphoXMVdxeAQU5ZMUvafvTFC"
              },
              "pending_coinbase_hash":
                "2n1FBQ8pMRjn7hN8UPt8LSfj6LvpngKAUGTL7feuJZygemYMEKfU"
            },
            "snarked_ledger_hash":
              "jxrU1KaQs2nwTU7nqGLp2i3JWSFJxtX7P1eYbrCsc19Ba8hcLdf",
            "genesis_ledger_hash":
              "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R",
            "snarked_next_available_token": "2",
            "timestamp": "1609646910000"
          },
          "consensus_state": {
            "blockchain_length": "319",
            "epoch_count": "0",
            "min_window_density": "1",
            "sub_window_densities": [
              "1", "1", "0", "2", "0", "2", "0", "2", "2", "0", "2"
            ],
            "last_vrf_output": "W9Elh_56uw3I_W5tgLQOS4RmEmdDhUs08AaDUv7IAgA=",
            "total_currency": "166016600000001000",
            "curr_global_slot": {
              "slot_number": "1618",
              "slots_per_epoch": "7140"
            },
            "global_slot_since_genesis": "1618",
            "staking_epoch_data": {
              "ledger": {
                "hash": "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R",
                "total_currency": "165950000000001000"
              },
              "seed": "2va9BGv9JrLTtrzZttiEMDYw1Zj6a6EHzXjmP9evHDTG3oEquURA",
              "start_checkpoint":
                "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x",
              "lock_checkpoint":
                "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x",
              "epoch_length": "1"
            },
            "next_epoch_data": {
              "ledger": {
                "hash": "jxX6VJ84HaafrKozFRA4qjnni4aPXqXC2H5vQLKSryNpKTXuz1R",
                "total_currency": "165950000000001000"
              },
              "seed": "2vaYF6yPnb7tDnxYSsmU3DNideZhsQJK54Ac3wBdyxFqWzds4GBA",
              "start_checkpoint":
                "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x",
              "lock_checkpoint":
                "3NLj877P2QHSSah2pzbCSsGgyU5YkW5BuhCS4Nh7YRCXV56SVKrw",
              "epoch_length": "320"
            },
            "has_ancestor_in_same_checkpoint_window": true,
            "block_stake_winner":
              "B62qrdSZKtFvxGj9pP6j8pzo3gQP2eH1hG32VpM3jhFHSeUrKGanvcy",
            "block_creator":
              "B62qrdSZKtFvxGj9pP6j8pzo3gQP2eH1hG32VpM3jhFHSeUrKGanvcy",
            "coinbase_receiver":
              "B62qrdSZKtFvxGj9pP6j8pzo3gQP2eH1hG32VpM3jhFHSeUrKGanvcy",
            "supercharge_coinbase": false
          },
          "constants": {
            "k": "290",
            "slots_per_epoch": "7140",
            "slots_per_sub_window": "7",
            "delta": "0",
            "genesis_state_timestamp": "1609355670000"
          }
        }
      },
      "protocol_state_proof": "<opaque>",
      "staged_ledger_diff": "<opaque>",
      "delta_transition_chain_proof": "<opaque>",
      "current_protocol_version": "1.1.0",
      "proposed_protocol_version": "<None>"
    },
    "hash": "3NKPE1DBqxFxG4HWS4qfv4nLMfHPGb6w8PUJK611iBxXTLDsDcT9"
  },
  "staged_ledger": "<opaque>",
  "just_emitted_a_proof": true,
  "transition_receipt_time": "2021-01-03T04:11:01.835790Z"
}
**Coda process exited with status code 137**
**2021-01-03 08:22:51** UTC [Info] Coda daemon is booting up; built with commit "[DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af" on branch "HEAD"

**Comment by mrmr1993** [comment] 2021-01-08 13:33
Exit code 137 indicates a kill of 9 (= 128 + 9). This is probably caused by an out-of-memory error.

**Comment by EmreNOP** [comment] 2021-01-08 13:59
if its, most probably not hardware related out of memory. 
That one was working on 32 Gb memory. (physical server)

**Comment by rpanic** [comment] 2022-01-09 12:33
Can confirm, this happened to me when my server was running out of memory.

**Comment by amc-ie** [comment] 2022-10-12 12:46
Is this still being observed? We have had added a lot of performance and stabilization improvements since this defect was last touched and we have not observed it internally. Please let me know along with any relevant information that may assist debugging, otherwise we will close this as part of our triage process. Thank you!

**Comment by EmreNOP** [comment] 2022-10-12 14:27
I dont have any additonal example for this issue. latest release is looking ok for this. please close.

**Comment by amc-ie** [comment] 2022-10-12 14:29
That is great to hear, thank you once again!

**Closed by amc-ie** 2022-10-12 14:29 UTC
Labels: triage
