### ISSUE TITLE
coda crash

### ISSUE THREAD

**Issue by erfan007p** [MinaProtocol/mina#7367] opened 2021-01-07 19:47 UTC
docker config locked to 4 core 8gb ram on wsl2
[coda_crash_report_2021-01-07_19-37-39.994029.tar.gz](https://github.com/MinaProtocol/mina/files/5783647/coda_crash_report_2021-01-07_19-37-39.994029.tar.gz)

**Comment by mrmr1993** [comment] 2021-01-08 12:57
```
{
  "timestamp": "2021-01-07 19:37:39.991123Z",
  "level": "Fatal",
  "source": {
    "module": "Init__Coda_run",
    "location": "File \"src/app/cli/src/init/coda_run.ml\", line 564, characters 2-26"
  },
  "message": "Unhandled top-level exception: $exn\nGenerating crash report",
  "metadata": {
    "exn": {
      "sexp": [
        "Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"40d71378-d2b3-3d2c-8184-3a20d683cd5a\", \"File \\\"src/lib/transition_router/transition_router.ml\\\", line 508, characters 61-68\")"
      ],
      "backtrace": [
        "Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57",
        "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 121, characters 6-26",
        "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1189, characters 29-65",
        "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1202, characters 18-30",
        "Called from file \"src/lib/network_pool/network_pool_base.ml\", line 101, characters 15-67",
        "Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 155, characters 28-37",
        "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
        "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
        "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
      ]
    },
    "host": "36.74.202.255",
    "peer_id": "12D3KooWKihNrQMMSjh2m1Nk167RM11zhapa6itXsUhKptVf2PqN",
    "pid": 13,
    "port": 8302
  }
}
```

This is a duplicate of #6949. Closing.

**Closed by mrmr1993** 2021-01-08 12:57 UTC
