### ISSUE TITLE
Daemon crashed

### ISSUE THREAD

**Issue by xni** [MinaProtocol/mina#7144] opened 2020-12-19 22:16 UTC
```
"backtrace": [
    "Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57",
    "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 121, characters 6-26",
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1165, characters 29-65",
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 1178, characters 18-30",
    "Called from file \"src/lib/network_pool/network_pool_base.ml\", line 101, characters 15-67",
    "Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 155, characters 28-37",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
```
[coda_crash_report_2020-12-19_21-47-01.525891.tar.gz](https://github.com/MinaProtocol/mina/files/5720211/coda_crash_report_2020-12-19_21-47-01.525891.tar.gz)

**Comment by garethtdavies** [comment] 2020-12-21 15:55
This is `Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference` and is a duplicate of #6537

**Comment by mrmr1993** [comment] 2021-01-08 13:02
Closing as a duplicate of #6949.

**Closed by mrmr1993** 2021-01-08 13:02 UTC
