### ISSUE TITLE
Money transfer can be made from A to A

### ISSUE THREAD

**Issue by donadel01** [MinaProtocol/mina#6937] opened 2020-12-04 12:06 UTC
Code:

coda client send-payment \
>   -amount 1 \
>   -receiver B62qkSLRRLB4smdHYDvkxmBXnuRVdThr9a8ZihU7RYrEg5T8VMwHxyB \
>   -fee 0.1 \
>   -sender B62qkSLRRLB4smdHYDvkxmBXnuRVdThr9a8ZihU7RYrEg5T8VMwHxyB
Dispatched payment with ID G8k9HJXpug4J4thR9me9Ft7CfDw9YRoEczbj8C81gfLWornLsEttZs64nj5eY8qzHPDGmuut2StkXFE4TJXZSjVraaNjtJqYfhoWuQ7nBpjfcCV2qZ3VV5MNFCe5Qk57CCmdzEzhQQY8tzQgWLpQUJnsWcZxPTJB1LjtiSd8aFPsEVeuurknVBxmFPGcCeFyAkbRdoUdMCUDmsmo5bmQ9mpAabJVaTBbu9Jyh7xVnupiwpfk3phBSXR64aVewWNjudFaByh3bD5Fi1vGj1dYYX9J9JgwqD1SovJHAA3sF5UFLCCHo98VEm7875D26UpXfbr6DxKADKh4HY5QvDeeG7G3dEakPoGHXSTHg3qqWNAucMSJ3oxKsfsSFLNkFHgRRNgz3jFVe

This operation is unnecessary

**Comment by mrmr1993** [comment] 2020-12-04 13:29
This is working as intended. For example, some valid uses are:
* cancelling a transaction by replacing it with an empty one (with a higher fee, so that it gets accepted by the network)
* cryptographically commiting to some data on the chain, via the account's receipt chain hash (which implicitly includes the transaction memo's hash)

It's also not worth the time or effort to explicitly ban this. Closing.

**Closed by mrmr1993** 2020-12-04 13:29 UTC
