### ISSUE TITLE
Duplicate (already submitted)

### ISSUE THREAD

**Issue by p-shahi** [MinaProtocol/mina#10367] opened 2022-03-04 01:49 UTC

**Comment by psteckler** [comment] 2022-03-15 21:17
What does "duplicate" mean here?

If the transaction has a duplicate nonce, it will be rejected with an invalid nonce.

If the nonce is different, there's no reason to reject the transaction (assuming there's still sufficient funds).

**Comment by deepthiskumar** [comment] 2022-03-16 18:20
Valid nonce but duplicate of a transaction that already exists in the pool

**Comment by deepthiskumar** [comment] 2022-03-16 18:21
Integration test

**Closed** 2022-04-25 17:05 UTC
