### ISSUE TITLE
[mainnet RC] stuck at lower block height

### ISSUE THREAD

**Issue by Comdex** [MinaProtocol/mina#8366] opened 2021-03-21 04:28 UTC
**The sync status is Synced, but the block height is behind.**
![nodestatus](https://user-images.githubusercontent.com/3725514/111892808-9dca9380-8a39-11eb-8287-e837cf05ed9d.PNG)

**Looking at the log, it seems to be related to libp2p validation expired**
![errlog](https://user-images.githubusercontent.com/3725514/111893850-b68a7780-8a40-11eb-854b-64053f096451.PNG)

As the logs are big, sharing it via googledrive
https://drive.google.com/file/d/16zxaJpAjm2PzVW-PHeKGh2VmimcVhEXC/view?usp=sharing

**Comment by mrmr1993** [comment] 2021-03-22 02:27
Closing this as a duplicate of #7555.

The underlying issue is that the verifier process sometimes isn't restarted if it exits or crashes, which prevents us from verifying any new blocks after that point. There's a fix in #8196, which we're currently testing and hope to release soon.

**Closed by mrmr1993** 2021-03-22 02:27 UTC
